Cr 2515 gcp
indeni/cloudrail-knowledge pull request #104
Opened 2021-06-29 08:24 UTC by Tomerva

2021-06-30 09:12 UTC, alonashkenazi requested changes

2021-06-30 09:12 UTC, alonashkenazi commented on cloudrail/knowledge/context/gcp/gcp_resource.py
> +        self.tf_resource_type: GcpResourceType = resource_type
I think that tf_ is misleading here, Tomer how do you see GCP support other IaC languages?

2021-06-30 09:12 UTC, alonashkenazi commented on cloudrail/knowledge/context/gcp/sql/gcp_sql_database_instance.py
> +        return f'https://console.cloud.google.com/sql/instances/{self.name}/'
should we have this in a const? https://console.cloud.google.com/sql/instances

2021-06-30 09:12 UTC, alonashkenazi commented on cloudrail/knowledge/rules/rule_metadata.py
> +    if provider == CloudProvider.AMAZON_WEB_SERVICES:
I would prefer to throw an exception if the provider is missing and don't default to GCP

2021-06-30 13:28 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/gcp_resource.py
> +        self.tf_resource_type: GcpResourceType = resource_type
I took another look on what tf_resource_type stands for (since its originated from AwsResource)

as i see it, we should build the iac_state differently to include: IAC provider (tf, CFN, etc) and the block type (aws_vpc, azurerm_vnet, etc..). Also, i dont think its correct for the AwsResource/AzureResource/GcpResource to have the resource type as a parameter for init, since we can do it generically.

We can discuss this further tomorrow. But either way, i think we need a new ticket for this change because its not a gcp-related change

2021-06-30 13:37 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/sql/gcp_sql_database_instance.py
> +        return f'https://console.cloud.google.com/sql/instances/{self.name}/'
i added GcpResource._BASE_URL = https://console.cloud.google.com

2021-07-07 09:06 UTC, alonashkenazi approved these changes

2021-07-07 09:06 UTC, alonashkenazi commented on cloudrail/knowledge/context/gcp/gcp_resource.py
> +        self.tf_resource_type: GcpResourceType = resource_type
Can you open a ticket for that?

2021-07-07 09:06 UTC, alonashkenazi commented on cloudrail/knowledge/rules/rule_metadata.py
> +    if provider == CloudProvider.AMAZON_WEB_SERVICES:
@Tomerva what do you think about this?

2021-07-07 09:25 UTC, Tomerva commented on cloudrail/knowledge/rules/rule_metadata.py
> +    if provider == CloudProvider.AMAZON_WEB_SERVICES:
i can add to CloudProvider this method:

`    def to_shorthand_string(self):
        if self == CloudProvider.AMAZON_WEB_SERVICES:
            return 'aws'
        return self.name.lower()`

and then: provider_name = provider.to_shorthand_string()

WDYT?

2021-07-07 09:27 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/gcp_resource.py
> +        self.tf_resource_type: GcpResourceType = resource_type
https://indeni.atlassian.net/browse/CR-2614

2021-07-07 11:54 UTC, alonashkenazi commented on cloudrail/knowledge/rules/rule_metadata.py
> +    if provider == CloudProvider.AMAZON_WEB_SERVICES:
looks better. Just add tests

2021-07-07 14:27 UTC, merged