s3 bucket resource updated for cfn support
indeni/cloudrail-knowledge pull request #107
Opened 2021-07-07 13:11 UTC by idan-aviv

2021-07-10 12:31 UTC, yi2020 requested changes

2021-07-10 12:31 UTC, yi2020 commented on cloudrail/knowledge/context/aws/s3/s3_bucket.py
> +    def get_attribute(self, cfn_attribute_name: str):
@idan-aviv @Viperain @alonashkenazi 
I don't like having this function in the context, it makes the context objects messy. The context should not care what is the source of the data (TF, CFN, Pulumi, live env).

2021-07-12 19:01 UTC, idan-aviv commented on cloudrail/knowledge/context/aws/s3/s3_bucket.py
> +    def get_attribute(self, cfn_attribute_name: str):
moved to cloudrail repository responsibility

2021-07-13 20:38 UTC, yi2020 approved these changes

2021-07-13 21:05 UTC, merged