Modifed resource and rule and tests
indeni/cloudrail-knowledge pull request #115
Opened 2021-07-13 17:19 UTC by Imanuel-Mizrahi

2021-07-13 17:57 UTC, yi2020 requested changes

2021-07-13 17:57 UTC, yi2020 commented on cloudrail/knowledge/rules/aws/non_context_aware/encryption_enforcement_rules/encrypt_at_rest/es_encrypt_at_rest_rule.py
> +                and float(es_domain.es_domain_version) >= 5.1)
What if the version has some character in it or some other issue in the future? Rule will crash.

2021-07-14 05:44 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/aws/non_context_aware/encryption_enforcement_rules/encrypt_at_rest/es_encrypt_at_rest_rule.py
> +                and float(es_domain.es_domain_version) >= 5.1)
Good point.
I found that we have actually only 2 versions which do not support es encryption (the list of versions are here: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-es-operations.html)
So, I switched to a static check against a set of these 2 versions

2021-07-14 05:48 UTC, yi2020 approved these changes

2021-07-14 07:24 UTC, Tomerva approved these changes

2021-07-14 09:32 UTC, merged