Cr 2388
indeni/cloudrail-knowledge pull request #121
Opened 2021-07-18 19:42 UTC by Tomerva

2021-07-19 04:15 UTC, Viperain approved these changes

2021-07-19 12:07 UTC, yi2020 approved these changes

2021-07-19 14:58 UTC, yi2020 requested changes

2021-07-19 14:58 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/context_aware/key_vault_diagnostic_logs_enabled_rule.py
> +                        f'The Key Vault `{key_vault.name}` does not have diagnostic logs enabled.',
Looking at Oleg's comments on CR-2388, we need to be clear here what's not enabled. For example, user may have enabled logs setting but not retention policy.

2021-07-20 15:09 UTC, Tomerva commented on cloudrail/knowledge/context/azure/keyvault/azure_monitor_diagnostic_setting.py
> +class AzureMonitorDiagnosticSetting(AzureResource):
add is_standalone implementation

2021-07-20 15:11 UTC, Tomerva commented on tests/knowledge/rules/azure/context_aware/test_key_vault_diagnostic_logs_enabled.py
> +            [AzureMonitorDiagnosticSetting('settings_name', 'keyvault_id', None), True],
add name

2021-07-20 15:15 UTC, Tomerva commented on cloudrail/knowledge/context/azure/keyvault/azure_monitor_diagnostic_setting.py
> +        self.monitoring: str = monitoring
rename to target_resource_id

2021-07-28 06:27 UTC, alonashkenazi approved these changes

2021-07-29 15:39 UTC, yi2020 commented on cloudrail/knowledge/context/azure/azure_resource.py
> +            self.with_aliases(_id)
This is something @Tomerva should look at

2021-07-30 08:31 UTC, Tomerva commented on cloudrail/knowledge/context/azure/azure_resource.py
> +            self.with_aliases(_id)
this is my change

2021-07-30 15:09 UTC, yi2020 approved these changes

2021-08-01 05:33 UTC, merged