CR-2466: not car azure ensure mysql servers enforce ssl
indeni/cloudrail-knowledge pull request #122
Opened 2021-07-19 09:42 UTC by Imanuel-Mizrahi

2021-07-19 12:22 UTC, yi2020 requested changes

2021-07-19 12:22 UTC, yi2020 commented on cloudrail/knowledge/context/azure/databases/azure_mysql_server.py
> +class AzureMySqlServer(AzureResource):
@Imanuel-Mizrahi you need to add this class to the documentation README files so they get pulled in.

2021-07-19 14:17 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/databases/azure_mysql_server.py
> +class AzureMySqlServer(AzureResource):
Thank you @yi2020 , added.

2021-07-22 13:21 UTC, Tomerva approved these changes

2021-07-26 13:55 UTC, yi2020 approved these changes

2021-07-26 14:15 UTC, merged