add az aws resource doc
indeni/cloudrail-knowledge pull request #123
Opened 2021-07-19 12:27 UTC by idan-aviv

2021-07-19 12:28 UTC, yi2020 requested changes

2021-07-19 12:28 UTC, yi2020 commented on cloudrail/knowledge/context/aws/ec2/availability_zone.py
> +    """
Also need to add this file to the README's in the context documentation

2021-07-19 12:33 UTC, idan-aviv commented on cloudrail/knowledge/context/aws/ec2/availability_zone.py
> +    """
are you talking about i.e. docs/context/aws/<aws-resource>/README.md?
if so i see it is related to TF only, az aws resource fetched only from real environment

2021-07-22 11:56 UTC, yi2020 commented on cloudrail/knowledge/context/aws/ec2/availability_zone.py
> +    """
The documentation is for the entire context model - the classes and their fields - it doesn't matter if they are built from TF, live or CFN.

2021-07-22 14:31 UTC, yi2020 commented on docs/context/aws/availability_zone/README.md
> +## ::: cloudrail.knowledge.context.aws.ec2.availability_zone.py
Wrong path. Should be aws/ec2

2021-11-10 09:23 UTC, closed without merging