CR-2467: [Not CAR] [Azure] Ensure PostgreSQL Servers are enforcing SSL
indeni/cloudrail-knowledge pull request #124
Opened 2021-07-19 13:59 UTC by Imanuel-Mizrahi

Modified resource, also in docs, added rule and tests

2021-07-21 16:22 UTC, yi2020 requested changes

2021-07-21 16:22 UTC, yi2020 commented on cloudrail/knowledge/context/azure/databases/azure_postgresql_server.py
> +            return 'PostgreSql Server'
PostgreSQL (capital Q and L)

2021-07-21 17:28 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/databases/azure_postgresql_server.py
> +            return 'PostgreSql Server'
Done

2021-07-22 08:41 UTC, alonashkenazi approved these changes

2021-07-25 14:18 UTC, yi2020 approved these changes

2021-07-26 10:23 UTC, Tomerva approved these changes

2021-07-27 07:41 UTC, merged