Feature/azure/cr 2272 webapp tls
indeni/cloudrail-knowledge pull request #125
Opened 2021-07-21 08:27 UTC by alonashkenazi

2021-07-21 11:47 UTC, alonashkenazi commented
![image](https://user-images.githubusercontent.com/544007/126483798-528800c0-eb93-41d4-b827-cee2c0f740a2.png)

2021-07-21 13:25 UTC, Tomerva commented on cloudrail/knowledge/context/azure/webapp/azure_app_service_config.py
>              auth_settings: Function app authentication settings.
not sure if this description is accurate.. did you mean App Service authentication setttings?

2021-07-21 13:26 UTC, Tomerva commented on cloudrail/knowledge/context/azure/webapp/azure_app_service_config.py
> +    def __init__(self, name, ftps_state: FtpsState, auth_settings: AuthSettings, minimum_tls_version: str) -> None:
minimum_tls_version should be optional

2021-07-21 13:29 UTC, Tomerva commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_authentication_enable_rule.py
> +            if app_service.app_service_config is not None and \
im not sure about this.. if there is no app service or no auth_settings then maybe we should raise issue?

2021-07-21 13:31 UTC, Tomerva commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_ftps_required_rule.py
> +            if app_service.app_service_config is not None and \
if app_service_config is None we shouldnt alert?

2021-07-21 13:36 UTC, Tomerva commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_use_latest_tls_version_rule.py
> +            if app_service.app_service_config is not None and \
if app_service_config is None, we shouldnt alert?

2021-07-21 13:47 UTC, yi2020 requested changes

2021-07-21 13:47 UTC, yi2020 commented on cloudrail/knowledge/context/azure/webapp/azure_app_service_config.py
> +        self.minimum_tls_version: str = minimum_tls_version or '1.2'
We don't put the default values in the context classes. Instead, this is set at the builder level. This is because the default value may be different in Terraform, Pulumi, live env, etc.

2021-07-21 13:47 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_use_latest_tls_version_rule.py
> +                    (tls_version := version.parse(app_service.app_service_config.minimum_tls_version) < version.parse('1.2')):
This is the first time we use this... where is this from?

2021-07-21 13:47 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_use_latest_tls_version_rule.py
> +                    (tls_version := version.parse(app_service.app_service_config.minimum_tls_version) < version.parse('1.2')):
Also what happens if the TLS version cannot be parsed by the version class?

2021-07-21 14:23 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/webapp/azure_app_service_config.py
>              auth_settings: Function app authentication settings.
yes. thx

2021-07-21 14:25 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/webapp/azure_app_service_config.py
> +        self.minimum_tls_version: str = minimum_tls_version or '1.2'
I checked with Oleg and the values are the same for both tf and Az
Why IaC will do something that is different than the cloud provider default?

2021-07-21 14:25 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/webapp/azure_app_service_config.py
> +    def __init__(self, name, ftps_state: FtpsState, auth_settings: AuthSettings, minimum_tls_version: str) -> None:
done

2021-07-21 14:26 UTC, alonashkenazi commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_authentication_enable_rule.py
> +            if app_service.app_service_config is not None and \
Yes. since the default for auth is false

2021-07-21 14:26 UTC, alonashkenazi commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_ftps_required_rule.py
> +            if app_service.app_service_config is not None and \
since the default is ALL

2021-07-21 14:27 UTC, alonashkenazi commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_use_latest_tls_version_rule.py
> +                    (tls_version := version.parse(app_service.app_service_config.minimum_tls_version) < version.parse('1.2')):
we used the version in AWS tls rule as well.

2021-07-21 14:28 UTC, alonashkenazi commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_use_latest_tls_version_rule.py
> +            if app_service.app_service_config is not None and \
Actually here the default is 1.2 so even if we don't have service config we shouldn't alert

2021-07-21 14:43 UTC, Tomerva commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_authentication_enable_rule.py
> +            if app_service.app_service_config is not None and \
so shouldnt you build auth_settings with false instead of being None?

2021-07-21 14:44 UTC, Tomerva commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_ftps_required_rule.py
> +            if app_service.app_service_config is not None and \
so the app_service_config should be iniitialized with ALL_ALLOWED no?

2021-07-21 14:45 UTC, Tomerva commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_use_latest_tls_version_rule.py
> +            if app_service.app_service_config is not None and \
so the app_service_config should be initialized with tls 1.2, no?

2021-07-21 14:47 UTC, Tomerva commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_use_latest_tls_version_rule.py
> +                    (tls_version := version.parse(app_service.app_service_config.minimum_tls_version) < version.parse('1.2')):
version package can probably parse all version formats

2021-07-21 18:55 UTC, alonashkenazi commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_authentication_enable_rule.py
> +            if app_service.app_service_config is not None and \
It is False, see class AuthSettings
Anyway, I'm removing the defaults for now

2021-07-21 19:00 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/webapp/azure_app_service_config.py
> +        self.minimum_tls_version: str = minimum_tls_version or '1.2'
ok. removed the defaults and move them to the builder

2021-07-21 19:03 UTC, yi2020 requested changes

2021-07-21 19:03 UTC, yi2020 commented on cloudrail/knowledge/context/azure/webapp/azure_app_service_config.py
> +    def __init__(self, name, ftps_state: FtpsState, auth_settings: AuthSettings, minimum_tls_version: Optional[str]) -> None:
minimum_tls_version shouldn't be Optional anymore

2021-07-22 11:51 UTC, Tomerva approved these changes

2021-07-22 12:37 UTC, yi2020 approved these changes

2021-07-22 12:38 UTC, merged