CR-2509: not car azure ensure sql servers audit enabled
indeni/cloudrail-knowledge pull request #126
Opened 2021-07-21 11:01 UTC by Imanuel-Mizrahi

2021-07-21 13:35 UTC, yi2020 requested changes

2021-07-21 13:35 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/ensure_sql_server_audit_enabled_rule.py
> +        for sql_server in env_context.sql_servers.values():
Why do we need .values()?

2021-07-21 13:35 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/ensure_sql_server_audit_enabled_rule.py
> +                        f'The {sql_server.get_type()} `{sql_server.get_friendly_name()}` does not have auditing enabled',
Note that this issue will be triggered for retention_in_days being between 0 and 90, but the evidence doesn't make that clear.

2021-07-21 14:00 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/azure/non_context_aware/ensure_sql_server_audit_enabled_rule.py
> +                        f'The {sql_server.get_type()} `{sql_server.get_friendly_name()}` does not have auditing enabled',
I used this logic based on the remediation steps mentioned in the rule_metadata for this rule.
@yi2020 ,perhaps we need to have different evidence strings? One for no audit enabled, and second if the audit enabled, but the retention is set to between 0 and 90?

2021-07-21 14:00 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/azure/non_context_aware/ensure_sql_server_audit_enabled_rule.py
> +        for sql_server in env_context.sql_servers.values():
I do not think we need, but this is the same way already implemented for other rule, I will just fix both

2021-07-21 16:26 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/ensure_sql_server_audit_enabled_rule.py
> +                        f'The {sql_server.get_type()} `{sql_server.get_friendly_name()}` does not have auditing enabled',
Yeah - split the if's and generate two string:

If it's not configured at all:
```
                        f'The {sql_server.get_type()} `{sql_server.get_friendly_name()}` does not have auditing enabled',
```

If not enough days:
```
                        f'The {sql_server.get_type()} `{sql_server.get_friendly_name()}` has auditing enabled, but for less than 90 days',
```

2021-07-22 08:50 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/azure_environment_context.py
> +        self.sql_server_extended_audit_policies: AliasesDict[AzureSqlServerExtendedAuditingPolicy] = sql_server_extended_audit_policies or AliasesDict()
@Imanuel-Mizrahi rename to mysql?

2021-07-22 08:50 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/databases/azure_mssql_server_extended_auditing_policy.py
> +class AzureSqlServerExtendedAuditingPolicy(AzureResource):
I think that you should mark this resource as not standalone

2021-07-22 08:50 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/databases/azure_mssql_server_extended_auditing_policy.py
> +        if not is_plural:
retrun 'SQL Server Extended Auditing ' +  'Policy'  if not is_plural else 'Policies'

2021-07-22 08:50 UTC, alonashkenazi commented on cloudrail/knowledge/rules/azure/non_context_aware/ensure_sql_server_audit_enabled_rule.py
> +            if not sql_server.extended_auditing_policy.log_monitoring_enabled \
Can the sql_server extended_auditing_policy be none?
should you add to your check:
if sql_server.extended_auditing_policy is not None?

2021-07-22 08:59 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/azure/non_context_aware/ensure_sql_server_audit_enabled_rule.py
> +            if not sql_server.extended_auditing_policy.log_monitoring_enabled \
No, the current builders will always fill in this field.

2021-07-22 09:00 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/azure_environment_context.py
> +        self.sql_server_extended_audit_policies: AliasesDict[AzureSqlServerExtendedAuditingPolicy] = sql_server_extended_audit_policies or AliasesDict()
no, mysql is a different resource in Azure, this should be only sql_server.
This is also how the sql_servers are named as well.

2021-07-22 09:03 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/databases/azure_mssql_server_extended_auditing_policy.py
> +class AzureSqlServerExtendedAuditingPolicy(AzureResource):
makes sense - changed it

2021-07-22 09:05 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/databases/azure_mssql_server_extended_auditing_policy.py
> +        if not is_plural:
nice one, done.

2021-07-22 14:11 UTC, Tomerva commented on cloudrail/knowledge/context/azure/databases/azure_sql_server.py
> +        return f'https://portal.azure.com/#@{self.tenant_id}/resource{self._id}/overview'
i think you missed a slash

2021-07-22 14:12 UTC, Tomerva approved these changes

2021-07-25 09:13 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/databases/azure_sql_server.py
> +        return f'https://portal.azure.com/#@{self.tenant_id}/resource{self._id}/overview'
Didn't missed it, the ID already includes the slash.
There is a context test for the "get_cloud_resource", and it's fine.

2021-07-25 14:28 UTC, yi2020 requested changes

2021-07-25 14:28 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/ensure_sql_server_audit_enabled_rule.py
> +            if not sql_server.extended_auditing_policy.log_monitoring_enabled \
The order here doesn't make sense. You do test for none, but after you already tried using extended_auditing_policy. This will fail.

2021-07-25 14:58 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/azure/non_context_aware/ensure_sql_server_audit_enabled_rule.py
> +            if not sql_server.extended_auditing_policy.log_monitoring_enabled \
Fixed order

2021-07-25 16:17 UTC, yi2020 approved these changes

2021-07-25 16:19 UTC, merged