AthenaWorkgroup: kms_key_id, kms_key_arn
indeni/cloudrail-knowledge pull request #127
Opened 2021-07-22 07:16 UTC by idan-aviv

2021-07-22 07:55 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/athena/athena_workgroup.py
> +
@idan-aviv , I am not sure where and why you need this change, but I think this should effect also other places:
1. Some rules, which use the "kms_key" field.
2. Some relations assigner functions.
Rather than that, looking good.

2021-07-22 08:03 UTC, alonashkenazi requested changes

2021-07-22 08:03 UTC, alonashkenazi commented on cloudrail/knowledge/context/aws/athena/athena_workgroup.py
> +                 kms_key_id: str = None):
we shouldn't have defaults in the object

2021-07-22 08:03 UTC, alonashkenazi commented on cloudrail/knowledge/context/aws/athena/athena_workgroup.py
> +        self.kms_key_id: str = kms_key_id or ArnParser().parse_arn(kms_key_arn)['resource'].replace('key/', '') if \
have you added ctx test case?

2021-07-22 08:29 UTC, idan-aviv commented on cloudrail/knowledge/context/aws/athena/athena_workgroup.py
> +        self.kms_key_id: str = kms_key_id or ArnParser().parse_arn(kms_key_arn)['resource'].replace('key/', '') if \
[here](https://bitbucket.org/indeni/cloud-rail/pull-requests/1546#chg-test/knowledge/context/aws/test_athena_workgroups.py)

2021-07-22 08:34 UTC, idan-aviv commented on cloudrail/knowledge/context/aws/athena/athena_workgroup.py
> +
@Imanuel-Mizrahi 
1. 'kms_key' renamed to 'kms_key_arn'
2. don't follow

 it shouldn't change any assigner logic cause it still comparing kms arn and now also added kms key id comparison (cloudformation works with key id only for static analysis

2021-07-22 08:35 UTC, idan-aviv commented on cloudrail/knowledge/context/aws/athena/athena_workgroup.py
> +                 kms_key_id: str = None):
@alonashkenazi don't understand this saying?

2021-07-22 08:36 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/athena/athena_workgroup.py
> +
all good, saw your changes in the relations assigner.
As for the rule, I think it's my bad, no rule use "kms_key".

2021-07-22 08:37 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/athena/athena_workgroup.py
> +            kms_key_arn: Set if KMS is used for encryption, this is the ARN of the key.
@idan-aviv , do we need to add "kms_key_id" here?

2021-07-22 12:51 UTC, yi2020 approved these changes
I've approved the PR, but it's only because I have the same comments as Alon.

2021-07-27 17:55 UTC, alonashkenazi approved these changes

2021-07-27 17:59 UTC, merged