CR-2495: [Not CAR] [Azure] Ensure Storage Account has default network access denied
indeni/cloudrail-knowledge pull request #128
Opened 2021-07-22 13:42 UTC by Imanuel-Mizrahi

2021-07-22 14:24 UTC, yi2020 requested changes

2021-07-22 14:24 UTC, yi2020 commented on cloudrail/knowledge/context/azure/storage/azure_storage_account_network_rule.py
> +class AzureStorageAccountNetworkRule(AzureResource):
Same comment

2021-07-25 12:53 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/storage/azure_storage_account.py
> +class AzureStorageAccount(AzureResource):
@yi2020 , I can see Alon already made the refactoring, but the class names still have Azure prefix.
I will leave it as is for now.

2021-07-25 12:53 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/storage/azure_storage_account.py
> +        return 'Storage ' + 'account' if not is_plural else 'accounts'
Done

2021-07-25 14:26 UTC, yi2020 requested changes

2021-07-25 14:26 UTC, yi2020 commented on cloudrail/knowledge/context/azure/storage/azure_storage_account.py
> +class AzureStorageAccount(AzureResource):
@alonashkenazi agree?

2021-07-25 14:26 UTC, yi2020 commented on cloudrail/knowledge/context/azure/storage/azure_storage_account.py
> +        self.network_rules: AzureStorageAccountNetworkRule = None
The field is called "network_rules", but only has one rule. Also, Azure supports multiple rules.

2021-07-25 14:26 UTC, yi2020 commented on cloudrail/knowledge/context/azure/storage/azure_storage_account_network_rule.py
> +            network_rules: The networking rules to allow or deny access from.
This isn't a field here

2021-07-25 14:26 UTC, yi2020 commented on cloudrail/knowledge/context/azure/storage/azure_storage_account_network_rule.py
> +            account_replication_type: The replication type of the storage account
This isn't a field here

2021-07-25 15:08 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/storage/azure_storage_account.py
> +        self.network_rules: AzureStorageAccountNetworkRule = None
@yi2020 , the way I see it, you can have a few ip_rules inside the network_rules block, but eventually, this is a one block.
So, the AzureStorageAccountNetworkRule can include "ip_rules" list, but currently, I didn't add the support for that, as it is not needed for this ticket.
But the way I see it, we have only one "network_rule" set per storage account.

2021-07-25 15:08 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/storage/azure_storage_account_network_rule.py
> +            network_rules: The networking rules to allow or deny access from.
True, my bad, removed it.

2021-07-26 10:16 UTC, Tomerva commented on cloudrail/knowledge/context/azure/storage/azure_storage_account.py
> +class AzureStorageAccount(AzureResource):
currently the Azure prefix for the resources are still set.
i personally think we can remove it, but in a separate ticket

2021-07-26 10:21 UTC, Tomerva commented on cloudrail/knowledge/context/azure/storage/azure_storage_account.py
> +        self.network_rules: AzureStorageAccountNetworkRule = None
This is pretty confusing..
if the attribute holds a single item, then the suffix 's' should not be included.

other than that, AzureStorageAccountNetworkRule should hold a list of rules? is this how the entity really represented?

2021-07-26 10:36 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/storage/azure_storage_account.py
> +        self.network_rules: AzureStorageAccountNetworkRule = None
@Tomerva , I used the same name convention as [TF docs for this resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account), there is a block named: "network_rules".
It will hold one set of config, and one of them could be a list (ip_rules).
@yi2020 , I also checked in the Azure console, it looks the same, you have one set of config, which inside you can specify a list of ip's (address range), but you cannot add multiple network_rules:
![image](https://user-images.githubusercontent.com/80635177/126975623-663933b8-9e92-4b8d-ab5a-eed85543a244.png)

I can name the attribute: "network_rule" or "networking" as appear in Azure console, if it's more suitable.

2021-07-26 13:54 UTC, yi2020 requested changes

2021-07-26 13:54 UTC, yi2020 commented on cloudrail/knowledge/context/azure/storage/azure_storage_account.py
> +        self.network_rules: AzureStorageAccountNetworkRule = None
First of all, you need to rename the class to be plural, because it represents a list within it (one instance of the class has an instance inside).
Secondly, you should add the list of rules, otherwise it's confusing.
Then, you don't need to change the attribute name.

2021-07-27 15:32 UTC, yi2020 approved these changes

2021-07-27 18:50 UTC, Tomerva approved these changes

2021-07-27 18:52 UTC, Tomerva commented on cloudrail/knowledge/context/azure/storage/azure_storage_account_network_rules.py
> +        self.ip_rules: Optional[list] = ip_rules
ip_rules should really be optional, or can it be always a list?
it will save us from writing code that checks if the list is None or not..

2021-07-28 05:50 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/storage/azure_storage_account.py
> +class AzureStorageAccount(AzureResource):
the change was in the builders not in the context, yet. We will address it in a different ticket

2021-07-28 05:57 UTC, alonashkenazi commented on cloudrail/knowledge/rules/azure/non_context_aware/ensure_storage_account_default_network_deny_rule.py
> +            if storage.network_rules.default_action != 'Deny':
should we have an enum for default_action?

2021-07-28 06:07 UTC, alonashkenazi commented on tests/knowledge/rules/azure/non_context_aware/test_ensure_storage_account_default_network_deny_rule.py
> +    def setUp(self):
see how we are using @parameterized.expand to reduce the amount of code

2021-07-28 06:07 UTC, alonashkenazi commented on tests/knowledge/rules/azure/non_context_aware/test_storage_account_secure_transfer.py
>      def test_storage_account_secure_transfer_enabled(self):
use @parameterized.expand(

2021-07-28 06:24 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/storage/azure_storage_account.py
> +    def __init__(self, storage_name: str, account_tier: str, account_replication_type: str, enable_https_traffic_only: bool) -> None:
No particular reason, it's just when I merged my branch with main, it was more convenient for me to add it to the end.

2021-07-28 06:25 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/azure/non_context_aware/ensure_storage_account_default_network_deny_rule.py
> +            if storage.network_rules.default_action != 'Deny':
it's possible, I guess there shouldn't be any changes for that at the future, so I will use ENUM

2021-07-28 06:28 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/storage/azure_storage_account_network_rules.py
> +        self.ip_rules: Optional[list] = ip_rules
Actually, in the builders, it will always be a list, so I will remove the optional.

2021-07-28 06:59 UTC, Imanuel-Mizrahi commented on tests/knowledge/rules/azure/non_context_aware/test_ensure_storage_account_default_network_deny_rule.py
> +    def setUp(self):
Done

2021-07-28 06:59 UTC, Imanuel-Mizrahi commented on tests/knowledge/rules/azure/non_context_aware/test_storage_account_secure_transfer.py
>      def test_storage_account_secure_transfer_enabled(self):
Done

2021-07-28 07:11 UTC, alonashkenazi approved these changes

2021-07-28 10:40 UTC, merged