Feature/azure/cr 2312 function app accessible via https
indeni/cloudrail-knowledge pull request #132
Opened 2021-07-26 21:17 UTC by alonashkenazi

2021-07-26 21:30 UTC, yi2020 requested changes

2021-07-26 21:30 UTC, yi2020 commented on cloudrail/knowledge/context/azure/webapp/azure_app_service.py
> -            app_service_config: App service configuration.
Why'd you remove this line?

2021-07-26 21:30 UTC, yi2020 commented on cloudrail/knowledge/context/azure/webapp/azure_function_app.py
> +        self.app_service_config: AzureAppServiceConfig = None
Missing from documentation

2021-07-26 22:04 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/webapp/azure_function_app.py
> +        self.app_service_config: AzureAppServiceConfig = None
Do you mean sote_config? If so, all sote_config props are in app_service_config (including auth_settings)

2021-07-26 22:09 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/webapp/azure_app_service.py
> -            app_service_config: App service configuration.
app_service_config is not an input to the contractor, should we document?

2021-07-26 22:17 UTC, yi2020 commented on cloudrail/knowledge/context/azure/webapp/azure_function_app.py
> +        self.app_service_config: AzureAppServiceConfig = None
Yes, because they are accessible as attributes of the class.

2021-07-26 22:18 UTC, yi2020 commented on cloudrail/knowledge/context/azure/webapp/azure_app_service.py
> -            app_service_config: App service configuration.
Yes

2021-07-26 22:46 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/webapp/azure_function_app.py
> +        self.app_service_config: AzureAppServiceConfig = None
added

2021-07-26 22:46 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/webapp/azure_app_service.py
> -            app_service_config: App service configuration.
added

2021-07-26 22:48 UTC, yi2020 approved these changes

2021-07-27 04:37 UTC, Imanuel-Mizrahi approved these changes

2021-07-27 06:14 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/webapp/azure_app_service_config.py
> +    def __init__(self, name, ftps_state: FtpsState, auth_settings: AuthSettings, minimum_tls_version: str, http2_enabled: str) -> None:
http2_enabled should be bool, but it's str here

2021-07-27 06:15 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/webapp/azure_function_app.py
> +        self.https_only = https_only
https_only was not initialized as bool

2021-07-27 17:07 UTC, merged