Cr 2875 cloudtrail
indeni/cloudrail-knowledge pull request #139
Opened 2021-07-27 21:51 UTC by cbc506

Adding rule for ensuring cloudtrail trail exists] CR-2875

2021-07-28 02:18 UTC, yi2020 requested changes

2021-07-28 02:18 UTC, yi2020 commented on cloudrail/knowledge/rules/aws/aws_rules_metadata.yaml
> +  remediation_steps_tf: Create terraform resource aws_cloudtrail and send logs to an S3 bucket
Please change remediation_steps_tf to `iac_remediation_steps` (new syntax)

2021-07-28 02:18 UTC, yi2020 commented on cloudrail/knowledge/rules/aws/aws_rules_metadata.yaml
> +  remediation_steps_console: Go to Cloudtrail and in the Dashboard click on Create trail, make sure multi-region is enabled.
Please change remediation_steps_console to `console_remediation_steps` (new syntax)

2021-07-28 02:18 UTC, yi2020 commented on cloudrail/knowledge/rules/aws/non_context_aware/log_validation_rules/ensure_cloudtrail_trail_exists.py
> +
Remove empty line

2021-07-28 02:18 UTC, yi2020 commented on tests/knowledge/rules/aws/non_context_aware/log_validation_rules/test_ensure_cloudtrail_trail_exists.py
> +
Remove empty line

2021-07-28 16:37 UTC, cbc506 commented
Fixed syntax and removed new lines

2021-07-28 16:38 UTC, cbc506 reviewed
Fixed syntax and removed new lines

2021-07-28 17:12 UTC, yi2020 commented
@Imanuel-Mizrahi can you review this as well? This'll need the cloudrail private-repo side too.

2021-07-28 17:15 UTC, yi2020 commented
@cbc506 some empty lines still showing. Can you double check?

2021-07-28 21:41 UTC, cbc506 commented
Thanks for the heads-up, I removed those as well.

2021-07-28 22:13 UTC, yi2020 commented
@cbc506 - I'm not sure if. you can see the CI results for this PR, but looks like there's some violations of Python best practices:

```
************* Module cloudrail.knowledge.rules.aws.non_context_aware.log_validation_rules.ensure_cloudtrail_trail_exists
/home/runner/work/cloudrail-knowledge/cloudrail-knowledge/cloudrail/knowledge/rules/aws/non_context_aware/log_validation_rules/ensure_cloudtrail_trail_exists.py:19: [C0303(trailing-whitespace), ] Trailing whitespace
/home/runner/work/cloudrail-knowledge/cloudrail-knowledge/cloudrail/knowledge/rules/aws/non_context_aware/log_validation_rules/ensure_cloudtrail_trail_exists.py:25: [C0303(trailing-whitespace), ] Trailing whitespace
/home/runner/work/cloudrail-knowledge/cloudrail-knowledge/cloudrail/knowledge/rules/aws/non_context_aware/log_validation_rules/ensure_cloudtrail_trail_exists.py:27: [C0303(trailing-whitespace), ] Trailing whitespace
/home/runner/work/cloudrail-knowledge/cloudrail-knowledge/cloudrail/knowledge/rules/aws/non_context_aware/log_validation_rules/ensure_cloudtrail_trail_exists.py:28: [C0304(missing-final-newline), ] Final newline missing
/home/runner/work/cloudrail-knowledge/cloudrail-knowledge/cloudrail/knowledge/rules/aws/non_context_aware/log_validation_rules/ensure_cloudtrail_trail_exists.py:28: [W0311(bad-indentation), ] Bad indentation. Found 12 spaces, expected 8
/home/runner/work/cloudrail-knowledge/cloudrail-knowledge/cloudrail/knowledge/rules/aws/non_context_aware/log_validation_rules/ensure_cloudtrail_trail_exists.py:24: [W1309(f-string-without-interpolation), EnsureCloudtrailTrailExists.execute] Using an f-string that does not have any interpolated variables
/home/runner/work/cloudrail-knowledge/cloudrail-knowledge/cloudrail/knowledge/rules/aws/non_context_aware/log_validation_rules/ensure_cloudtrail_trail_exists.py:6: [W0611(unused-import), ] Unused Account imported from cloudrail.knowledge.context.aws.account.account
```

2021-07-29 11:49 UTC, Imanuel-Mizrahi requested changes

2021-07-29 11:49 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/aws/non_context_aware/log_validation_rules/ensure_cloudtrail_trail_exists.py
> +            return True
As this rule iterate over the accounts, I think we should change the "should_run_rule" to check for env_context.accounts. In the current way, running with --no-cloud-account might cause issues.

2021-07-29 18:12 UTC, cbc506 commented on cloudrail/knowledge/rules/aws/non_context_aware/log_validation_rules/ensure_cloudtrail_trail_exists.py
> +            return True
Good point, Imanuel. I'll test that scenario but it makes sense.

2021-08-01 00:00 UTC, cbc506 commented
Added the check as suggested by Imanuel and fixed pylint errors

2021-08-31 16:45 UTC, yi2020 approved these changes

2021-08-31 17:45 UTC, cbc506 commented on cloudrail/knowledge/rules/aws/non_context_aware/log_validation_rules/ensure_cloudtrail_trail_exists.py
> +            return True
Fixed logic and format in latest commit

2021-08-31 17:50 UTC, yi2020 commented
@Imanuel-Mizrahi good to go now?

2021-08-31 17:54 UTC, yi2020 commented
@alonashkenazi @olozz check-binary is blocking this PR for some reason.

2021-08-31 18:46 UTC, olozz commented
> @alonashkenazi @olozz check-binary is blocking this PR for some reason.

@cbc506 this is because of forked br, will be working on it tomorrow

2021-09-01 05:35 UTC, Imanuel-Mizrahi requested changes

2021-09-01 05:35 UTC, Imanuel-Mizrahi commented on tests/knowledge/rules/aws/non_context_aware/log_validation_rules/test_ensure_cloudtrail_trail_exists.py
> +    def test_ensure_cloudtrail_trail_exists_pass(self):
This test seems to be missing the "account" in the context, I guess it simply skip the rule, so it is considered as "Success".

2021-09-01 11:11 UTC, olozz commented
> > @alonashkenazi @olozz check-binary is blocking this PR for some reason.
> 
> @cbc506 this is because of forked br, will be working on it tomorrow

@cbc506 should be ok now

2021-09-03 01:18 UTC, cbc506 commented on tests/knowledge/rules/aws/non_context_aware/log_validation_rules/test_ensure_cloudtrail_trail_exists.py
> +    def test_ensure_cloudtrail_trail_exists_pass(self):
you are right, I added that to the tests

2021-09-04 03:21 UTC, cbc506 commented on tests/knowledge/rules/aws/non_context_aware/log_validation_rules/test_ensure_cloudtrail_trail_exists.py
> +    def test_ensure_cloudtrail_trail_exists_pass(self):
Please try to merge again, it failed because it did not like relative path so I checked the other rules and left the absolute path as in those

2021-09-07 16:47 UTC, yi2020 commented
@cbc506 still failing. This seems to have been caused by recent changes:
1. Changing the accounts in the context, 
2. Changing the format of remediation steps in metadata.

Are you OK working on this or do you prefer we jump in to assist?

2021-09-08 03:09 UTC, cbc506 commented
> @cbc506 still failing. This seems to have been caused by recent changes in the cloudrail-knowledge repo:
> 
> 1. Changing the accounts in the context,
> 2. Changing the format of remediation steps in metadata.
> 
> Sorry about that.
> 
> Are you OK working on this or do you prefer we jump in to assist?

Thanks for the pointer Yoni. If you guys already know the issue please jump in as I was looking at the error and it would take me a while to figure out.

2021-09-08 15:51 UTC, yi2020 commented
@cbc506 done. @Imanuel-Mizrahi please review and see if approved.

2021-09-09 05:03 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/aws/non_context_aware/log_validation_rules/ensure_cloudtrail_trail_exists.py
> +                        account, account ))
Just remove this space after the last "account".

2021-09-09 05:03 UTC, Imanuel-Mizrahi approved these changes

2021-09-10 15:48 UTC, merged