RemediationSteps: add new rule metadata class
indeni/cloudrail-knowledge pull request #144
Opened 2021-08-04 14:20 UTC by idan-aviv

2021-08-05 23:57 UTC, yi2020 requested changes

2021-08-05 23:57 UTC, yi2020 commented on cloudrail/knowledge/rules/rule_metadata.py
> -    iac_remediation_steps: str
1. This is breaking backwards compatibility - if someone wrote a custom rule it no longer will work. (@alonashkenazi )
2. All existing rules need to be updated to use the new format.

2021-08-06 06:19 UTC, alonashkenazi commented on cloudrail/knowledge/rules/rule_metadata.py
> -    iac_remediation_steps: str
@yi2020 The ctx has a lot of problems, we will need to refactor it. At this point, since we don't have customers that are using the ctx (like external API) I prefer to keep and improve the ctx object modeling and take the "risk"

2021-08-17 12:41 UTC, idan-aviv commented on cloudrail/knowledge/rules/rule_metadata.py
> -    iac_remediation_steps: str
@yi2020 if no additional comments please approve, thanks

2021-08-18 13:01 UTC, yi2020 approved these changes

2021-08-19 09:52 UTC, merged