Feature/cr 2263 non car diagnostic logs enabled in app services
indeni/cloudrail-knowledge pull request #145
Opened 2021-08-08 12:07 UTC by lirshindalman

2021-08-08 12:44 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/webapp/diagnostic_logs.py
> +    def __init__(self, detailed_error_logging_enabled: bool, http_logging_enabled: bool, request_tracing_enabled: bool) -> None:
__init__ shouldn't have a return type. remove the -> None

2021-08-08 12:44 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/webapp/azure_app_service_config.py
> +    def __init__(self, name, ftps_state: FtpsState, auth_settings: AuthSettings, minimum_tls_version: str, http2_enabled: bool, logs: DiagnosticLogs) -> None:
__init__ shouldn't have a return type. remove the -> None

2021-08-08 12:44 UTC, alonashkenazi commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_non_car_diagnostic_logs_enabled_in_app_services_rule.py
> +            logs: List[str] = []
rename to evidance

2021-08-08 12:44 UTC, alonashkenazi commented on tests/knowledge/rules/azure/non_context_aware/test_app_service_non_car_diagnostic_logs_enabled_in_app_services.py
> +            self.assertEqual(1, len(result.issues))
I suggest that in your case you will also assert on the evidence string

2021-08-08 13:03 UTC, Tomerva commented on cloudrail/knowledge/context/azure/webapp/azure_app_service_config.py
missing documentation of the new attribute

2021-08-08 13:06 UTC, Tomerva commented
need to update docs/context/azure/webapp/README.md to include the new rule

2021-08-12 08:24 UTC, alonashkenazi requested changes

2021-08-12 08:24 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/webapp/diagnostic_logs.py
> +class DiagnosticLogs:
@lirshindalman you need to add documentation for this as well

2021-08-12 09:20 UTC, Tomerva commented on cloudrail/knowledge/rules/azure/azure_rules_metadata.yaml
>  templates:
why did you remove the brackets ( < > ) ? the links in the metadata yaml should be surrounded by them

2021-08-12 13:58 UTC, yi2020 requested changes

2021-08-12 13:58 UTC, yi2020 commented on cloudrail/knowledge/context/azure/webapp/azure_app_service_config.py
> +            logs: The DiagnosticLogs indicate if the logs (detailed error messages, HTTP logging, and failed requests tracing) are  enabled or not
extra space in `are  enabled`

2021-08-12 13:58 UTC, yi2020 commented on cloudrail/knowledge/context/azure/webapp/diagnostic_logs.py
> +                detailed_error_logging_enabled: Indicate if the detailed error logging enable or disable.
`is enabled or disabled`, same for the others.

2021-08-12 13:58 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_non_car_diagnostic_logs_enabled_in_app_services_rule.py
> +            if app_service.app_service_config is not None and app_service.app_service_config.logs is not None:
what if .logs is None?

2021-08-12 13:58 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_non_car_diagnostic_logs_enabled_in_app_services_rule.py
> +                    Issue('\n'.join(evidence), app_service, app_service))
Did you try to see how this output would look like in the CLI and the web UI? We don't normally join evidences using a newline character.

2021-08-12 13:58 UTC, yi2020 commented on cloudrail/knowledge/context/azure/webapp/diagnostic_logs.py
> +class DiagnosticLogs:
In order for this class to be in the READMEs, you need to add a reference to. this Python package in the relevant location in the readmes.

2021-08-12 15:23 UTC, lirshindalman commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_non_car_diagnostic_logs_enabled_in_app_services_rule.py
> +            if app_service.app_service_config is not None and app_service.app_service_config.logs is not None:
I handle it in the builder, if there are no logs the default is False and then the issue will be with the 3 cases

2021-08-13 17:00 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_non_car_diagnostic_logs_enabled_in_app_services_rule.py
> +            if app_service.app_service_config is not None and app_service.app_service_config.logs is not None:
That doesn't make sense, you're "abusing" the type-unsafety of Python. If you declare that this field needs to have a certain object in it, then it can either have that object or None. It shouldn't have False (even if Python supports it). @alonashkenazi @ori-bar  we should generally think about increasing type-safety.

2021-08-13 17:01 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_non_car_diagnostic_logs_enabled_in_app_services_rule.py
> +                    Issue(', '.join(evidence), app_service, app_service))
Use a period instead of a comma for joining. The reason is that you have a capital T at the beginning of each evidence, and there shouldn't be a capital letter following a comma in English.

2021-08-13 17:05 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_non_car_diagnostic_logs_enabled_in_app_services_rule.py
> +            if app_service.app_service_config is not None and app_service.app_service_config.logs is not None:
I'm sorry @lirshindalman I misunderstood your comment. I now looked at how you do it in the builders:
```
        Scanner:
                return AzureAppServiceConfig(name=attributes['name'],
                                     ftps_state=FtpsState(attributes['properties']['ftpsState']),
                                     auth_settings=AuthSettings(attributes['properties']['siteAuthEnabled']),
                                     minimum_tls_version=attributes['properties']['minTlsVersion'],
                                     http2_enabled=attributes['properties']['http20Enabled'])
                                     http2_enabled=attributes['properties']['http20Enabled'],
                                     logs=DiagnosticLogs(detailed_error_logging_enabled,
                                                         http_logging_enabled,
                                                         request_tracing_enabled))

        Terraform:
        logs: Optional[DiagnosticLogs] = DiagnosticLogs(False, False, False)
        if logs_dict := self._get_known_value(attributes, 'logs'):
            logs.detailed_error_logging_enabled = self._get_known_value(logs_dict[0], 'detailed_error_messages_enabled', False)
            logs.request_tracing_enabled = self._get_known_value(logs_dict[0], 'failed_request_tracing_enabled', False)
            logs.http_logging_enabled = True if self._is_known_value(logs_dict[0], 'http_logs') else False
```

Which means the field will not be empty with these builders. However, there are other infrastructure-as-code languages in the world, even for Azure. We plan on supporting those at some point - like Pulumi, Bicep, ARM. If the developer who writes the builders for those provides a None for this field, the rule will crash. Unfortunately, this has happened many times, even last week, and so we need to build the rules in a way where they're None-proof. So my comment still stands.

2021-08-15 06:45 UTC, Tomerva approved these changes

2021-08-16 12:22 UTC, alonashkenazi approved these changes

2021-08-16 13:27 UTC, yi2020 requested changes

2021-08-16 13:27 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_non_car_diagnostic_logs_enabled_in_app_services_rule.py
> +                    app_service.app_service_config['logs'] = DiagnosticLogs(False, False, False)
Rules are not allowed to modify the content within a a context object's class.

2021-08-16 13:29 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_non_car_diagnostic_logs_enabled_in_app_services_rule.py
> +                    app_service.app_service_config['logs'] = DiagnosticLogs(False, False, False)
The solution here would be to add this in the case of None:
```
f'The web app `{app_service_name}` does not have logging enabled')
```

Make sure not to run the other if's if the `.logs` is None, as the rule will crash if you do.

2021-08-16 19:41 UTC, yi2020 approved these changes

2021-08-17 09:09 UTC, merged