Added rule KubernetesClusterRbacEnabledRule
indeni/cloudrail-knowledge pull request #149
Opened 2021-08-08 16:18 UTC by Tomerva

2021-08-08 20:15 UTC, alonashkenazi approved these changes

2021-08-08 20:25 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/aks/azure_kubernetes_cluster.py
> +        self.enable_rbac: bool = enable_rbac
Something to think about:
the name that you gave to the prop is can be misleading as there is azure_rbac_enabled prop as well in tf, maybe call it 
  role_based_access_control_enable? 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#azure_rbac_enabled

The prop in the scanner is enableRBAC so this I don't know what is the right answer...

2021-08-09 06:02 UTC, Tomerva commented on cloudrail/knowledge/context/azure/aks/azure_kubernetes_cluster.py
> +        self.enable_rbac: bool = enable_rbac
i named it according to scanner data.. also role_based_access_control_enable is practically the same as rbac_enable so i dont see a reason to change it

2021-08-09 22:06 UTC, yi2020 requested changes

2021-08-09 22:06 UTC, yi2020 commented on mkdocs.yml
> +      - 'aks': 'context/azure/aks/README.md'
Can you add these entries sorted A-Z? I realize Azure is messy here, but just noticed it due to this one starting with a.

2021-08-10 13:49 UTC, yi2020 approved these changes

2021-08-11 15:06 UTC, merged