CR-2995
indeni/cloudrail-knowledge pull request #159
Opened 2021-08-16 11:51 UTC by lirshindalman

2021-08-16 11:59 UTC, Imanuel-Mizrahi approved these changes

2021-08-16 12:36 UTC, alonashkenazi approved these changes

2021-08-16 12:53 UTC, Tomerva commented on cloudrail/knowledge/context/aws/s3/s3_bucket.py
> +        self.is_logger = False
add documentation

2021-08-16 12:53 UTC, Tomerva commented on .github/workflows/md-link-check.config.json
> +      "pattern": "^https://www.indeni.com/cloudrail"
what is this?

2021-08-16 12:59 UTC, alonashkenazi requested changes
branch name need to follow this: <feature>/<Jira-ticket>-<description>

2021-08-16 13:32 UTC, yi2020 commented
@lirshindalman please name your PRs with the full name of the ticket, like you did for https://github.com/indeni/cloudrail-knowledge/pull/145

2021-08-16 13:35 UTC, yi2020 requested changes

2021-08-16 13:35 UTC, yi2020 commented on .github/workflows/md-link-check.config.json
> +      "pattern": "^https://www.indeni.com/cloudrail"
This is a pattern to ignore the link to our main website as part of the verification of links in our README.md. @lirshindalman this is failing because the indeni.com website is apparently down. I got an alert about it overnight and we've now reached out to the hosting team to handle this. The pattern should not be added as the website should normally be functioning and not break your CI.

2021-08-16 13:35 UTC, yi2020 commented on cloudrail/knowledge/context/aws/s3/s3_bucket.py
> +                 policy: S3Policy = None, is_logger: bool = False):
Add documentation for this field.

2021-08-16 23:19 UTC, yi2020 requested changes

2021-08-16 23:19 UTC, yi2020 commented on cloudrail/knowledge/context/aws/s3/s3_bucket.py
> +            is_logger: Indicate if this s3bucket is target_bucket in a different s3bucket - default is false
s3bucket -> S3 Bucket
or you could call it simply "bucket"

AWS is pretty sensitive about how their objects/services are written.

When you say "target_bucket", the reader doesn't necessarily understand what that means. There's no such property in this resource.

So I suggest writing this:
`is_logger: Indicates if this bucket is the target bucket for logging of another bucket.`

2021-08-17 13:56 UTC, yi2020 approved these changes

2021-08-18 09:46 UTC, alonashkenazi approved these changes

2021-08-18 09:47 UTC, merged