CR-2340: [Not CAR] [Azure] Ensure VMs and VMSSs only use managed disks
indeni/cloudrail-knowledge pull request #163
Opened 2021-08-18 15:32 UTC by Imanuel-Mizrahi

2021-08-18 17:33 UTC, yi2020 requested changes

2021-08-18 17:33 UTC, yi2020 commented on cloudrail/knowledge/context/azure/vm/azure_virtual_machine.py
> +@dataclass
Add a line break

2021-08-18 17:33 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/ensure_vms_and_vmss_use_managed_disks_rule.py
> +            if issues_found := self._get_unmanaged_disks_usage(virtual_machine):
Why do you need the if? Why not simply issues.extend with the result of the func?

2021-08-18 17:33 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/ensure_vms_and_vmss_use_managed_disks_rule.py
> +        if not vm_entity.disk_settings.os_disk.is_managed_disk:
what if disk_settings is none, or os_disk is none?

2021-08-18 17:33 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/ensure_vms_and_vmss_use_managed_disks_rule.py
> +        elif (any(not disk.is_managed_disk for disk in vm_entity.disk_settings.data_disks)):
same comment about none

2021-08-18 17:33 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/ensure_vms_and_vmss_use_managed_disks_rule.py
> +                        f"The {vm_entity.get_type()} `{vm_entity.get_friendly_name()}` is using an unmanaged disk for both it's os_disk and one of it's managed disks",
it's -> its

2021-08-18 17:33 UTC, yi2020 commented on mkdocs.yml
> +      - 'vmss': 'context/azure/vmss/README.md'
Please add this in A-Z order (so before webapp)

2021-08-19 09:16 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/azure/non_context_aware/ensure_vms_and_vmss_use_managed_disks_rule.py
> +        elif (any(not disk.is_managed_disk for disk in vm_entity.disk_settings.data_disks)):
@yi2020 , about both your comments of None:
os_disk - is a mandatory field, as part of the resource, it can never be None.
data_disks - are initialized with empty list, so if it's empty the iteration will not proceed, and we will have no data, but we will not crash.
Anyway, based on my tests, it seems like you cannot combine managed and unmanaged disks on the same VM, so I will change the rule...

2021-08-19 16:08 UTC, yi2020 requested changes

2021-08-19 16:08 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/ensure_vms_and_vmss_use_managed_disks_rule.py
> +            if not virtual_machine.disk_settings.os_disk.is_managed_disk:
What if disk_settings or os_disk are missing?

2021-08-19 17:57 UTC, yi2020 approved these changes

2021-08-22 05:36 UTC, Tomerva approved these changes

2021-08-22 06:40 UTC, Tomerva commented on cloudrail/knowledge/context/azure/vmss/azure_virtual_machine_scale_set.py
> +        self.network_interfaces_config: List[AzureNetworkInterface] = network_interfaces_config
fix thee type

2021-08-23 14:18 UTC, merged