Cr 2493 non car storage account public access
indeni/cloudrail-knowledge pull request #165
Opened 2021-08-19 12:46 UTC by doronafota

2021-08-19 15:22 UTC, Imanuel-Mizrahi requested changes

2021-08-19 15:22 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/azure/non_context_aware/storage_account_public_access_rule.py
> +
Please remove this space

2021-08-19 15:22 UTC, Imanuel-Mizrahi commented on tests/knowledge/rules/azure/non_context_aware/test_storage_account_public_access_rule.py
> +            ['storage_account_public_access_enabled', None, False],
I am not sure you need to add a test case for None. Is there any scenario in which this could be None?

2021-08-22 10:51 UTC, Imanuel-Mizrahi approved these changes

2021-08-23 07:39 UTC, Tomerva commented on cloudrail/knowledge/context/azure/storage/azure_storage_account.py
> +    def __init__(self, storage_name: str, account_tier: str, account_replication_type: str,
__init__ should not have return type

2021-08-23 08:46 UTC, Tomerva approved these changes

2021-08-29 06:15 UTC, merged