Added rule FsxWindowsFileSystemEncryptedAtRestWithCustomerManagedCmkRule
indeni/cloudrail-knowledge pull request #172
Opened 2021-08-24 14:39 UTC by Tomerva

2021-08-24 15:42 UTC, Imanuel-Mizrahi requested changes

2021-08-24 15:42 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/fsx/fsx_windows_file_system.py
> +    def get_arn(self) -> str:
@Tomerva , if the resource is tagable, we need to fill in some ARN.
It's because the tags are being filled to each resource, while matching the ARN and the tags list from AWS.

2021-08-24 15:46 UTC, Imanuel-Mizrahi approved these changes

2021-08-24 16:39 UTC, yi2020 approved these changes

2021-08-24 16:39 UTC, yi2020 commented on cloudrail/knowledge/context/aws/fsx/fsx_windows_file_system.py
> +    def get_arn(self) -> str:
@Imanuel-Mizrahi @Tomerva @Viperain is there a way to add this logic to a test, so resources aren't added with this issue?

2021-08-25 05:44 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/fsx/fsx_windows_file_system.py
> +    def get_arn(self) -> str:
While working on tags for drift, I found that we actually have 2 ways to get the "tags" for AWS resource **scanner**.
One will be using the ARN, the other will try to get "tags" from the API call of the resource itself, if there is one.
So, to be honest, we do not need always the "get_arn" for a "tagable" resource, but only if the "tags" does not appear in the same API call which we build the resource with.
So, I guess we still need the programmer to manually check it.

2021-08-25 15:29 UTC, merged