defender sql server on vm rule
indeni/cloudrail-knowledge pull request #179
Opened 2021-08-30 13:03 UTC by doronafota

2021-08-30 13:13 UTC, Imanuel-Mizrahi approved these changes

2021-08-30 14:48 UTC, yi2020 requested changes

2021-08-30 14:48 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/azure_rules_metadata.yaml
> +    - Sql Servers Virtual Machines
Please make sure you write resource names in the way the cloud provider does. In this case it would be "SQL Server on Virtual Machines"

2021-08-30 14:48 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/azure_rules_metadata.yaml
> +  name: Ensure Azure Defender for SQL servers on machines is enabled
SQL Servers on Virtual Machines

2021-08-30 14:48 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/azure_rules_metadata.yaml
> +    - Sql Servers Virtual Machines
Also fix in the following lines in this metadata

2021-08-30 14:48 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/azure_defender_enabled_rules.py
> +        return f"Azure Defender is not enabled for SQL servers on machines in the subscription `{subscription_id}`."
SQL Servers on Virtual Machines

2021-08-31 14:44 UTC, yi2020 approved these changes

2021-08-31 14:48 UTC, merged