Feature/cr 3134 aws sqs queue policy modification
indeni/cloudrail-knowledge pull request #195
Opened 2021-09-05 13:02 UTC by lirshindalman

2021-09-12 07:00 UTC, Imanuel-Mizrahi requested changes

2021-09-12 07:00 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources/apigateway/rest_api_gw.py
> +        self.resource_based_policy: RestApiGwPolicy = None
Why we only add "resource_based_policy" just for this resource, I think we need to add it to all the other resources, no?
In addition, perhaps we can simply add to the "ResourceBasedPolicy" class, the attribute: "resource_based_policy", so all who inherits from it, will already have it, right?

2021-09-12 07:02 UTC, Imanuel-Mizrahi commented
@lirshindalman , a general recommendation about this PR.
As this change affect many resources, I would say that it is actually better to create a beta version, and make sure all server tests pass, before we proceed to merge this PR.
We might have some unexpected surprises...

2021-09-12 09:39 UTC, lirshindalman commented on cloudrail/knowledge/context/aws/resources/apigateway/rest_api_gw.py
> +        self.resource_based_policy: RestApiGwPolicy = None
but each resource has a different resource_based_policy. example LambdaPolicy or S3Policy

2021-09-26 09:51 UTC, Tomerva requested changes

2021-09-26 09:51 UTC, Tomerva commented on cloudrail/knowledge/context/aws/aws_connection_builder.py
> +                        if hasattr(target_resource, 'resource_based_policy') and target_resource.resource_based_policy \
hasattr is a very "hacky" solution, in most cases it should be avoided and should be solved by proper OOP design, like inheritance as discussed

2021-09-26 09:51 UTC, Tomerva commented on cloudrail/knowledge/context/aws/aws_connection_builder.py
> +                        if hasattr(target_resource, 'resource_based_policy') and target_resource.resource_based_policy \
i see you added class AwsResourceWithBasedPolicy. so instead of hasattr you should check if isinstance(target_resource, AwsResourceWithBasedPolicy)

2021-09-26 09:51 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources/apigateway/rest_api_gw.py
> +class RestApiGw(AwsResource):
should inherit from AwsResourceWithBasedPolicy

2021-09-26 09:51 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources/aws_resource_with_based_policy.py
> +class AwsResourceWithBasedPolicy(AwsResource):
need to figure out a better name for this class.. i think PoliciedResource is ok, WDYT?

2021-09-26 09:51 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources/lambda_/lambda_function.py
> +class LambdaFunction(NetworkEntity, AwsResource, AwsClient):
should also inherit from your new class, like every resource that has resource_based_policy attribute. please search for all occurrences of resource_based_policy

2021-10-04 15:58 UTC, lirshindalman commented on cloudrail/knowledge/context/aws/resources/apigateway/rest_api_gw.py
> +class RestApiGw(AwsResource):
inherit from PoliciedResource

2021-10-04 16:12 UTC, Imanuel-Mizrahi approved these changes

2021-10-04 16:12 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources/es/elastic_search_domain.py
> +            resource_based_policy: The resource policy used with the domain.
I guess we can remove the "resource_based_policy" field here as well.

2021-10-04 16:12 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources/lambda_/lambda_function.py
> +            resource_based_policy: The resource policy of the Lambda Function, if any is defined.
Remove the "resource_based_policy" field

2021-10-04 16:12 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources/secretsmanager/secrets_manager_secret.py
> +            resource_based_policy: The resource policy to use with this secret, if any.
Remove the "resource_based_policy" field

2021-10-05 05:59 UTC, Tomerva requested changes

2021-10-05 05:59 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources/aws_policied_resource.py
> +    This class is the parent of all resources that have a based policy.
that have a **resource** based policy

2021-10-05 05:59 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources/es/elastic_search_domain.py
> +        PoliciedResource.__init__(self, account, region, AwsServiceName.AWS_ELASTIC_SEARCH_DOMAIN)
these 2 lines basically do the same thing

read this https://stackoverflow.com/questions/3277367/how-does-pythons-super-work-with-multiple-inheritance

2021-10-05 05:59 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources/lambda_/lambda_function.py
> +        PoliciedResource.__init__(self, account, region, AwsServiceName.AWS_LAMBDA_FUNCTION,
same comment (https://stackoverflow.com/questions/3277367/how-does-pythons-super-work-with-multiple-inheritance)

2021-10-05 05:59 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources/lambda_/lambda_function.py
> +        return None
if it can return None, the return type should be Optional[str]

also please make sure all places that use this function, use it safely (IE, know that it can be None or it doesnt matter to them)

2021-10-05 05:59 UTC, Tomerva commented on cloudrail/knowledge/rules/aws/non_context_aware/policy_wildcard_violation/ensure_policy_not_use_wildcard_actions_rules.py
>      def _get_entity_policy(entity: CloudWatchLogsDestination) -> Policy:
this method is redundant here
because all these resources are of the same group (PoliciedResource) they all have resource_based_policy attribute.

so instead of implementing _get_entity_policy everywhere, you can either implement it on EnsurePolicyNotUseWildcardRules once, or (the more preferred way) change the return type of _get_rule_entities to `Optional[List[PoliciedResource]]` and then instead of doing `policy = self._get_entity_policy(entity)` you can just access it (`entity.resource_based_policy`) without needing to check the type with isinstance

2021-10-05 08:33 UTC, lirshindalman commented on cloudrail/knowledge/context/aws/resources/es/elastic_search_domain.py
> +        PoliciedResource.__init__(self, account, region, AwsServiceName.AWS_ELASTIC_SEARCH_DOMAIN)
In this case where each class has its own positional arguments for its init, it butter to call each class's own init method.

2021-10-05 15:26 UTC, Tomerva approved these changes

2021-10-06 13:03 UTC, merged