Feature/cr 3114 update origin func
indeni/cloudrail-knowledge pull request #211
Opened 2021-09-12 12:41 UTC by idan-aviv

2021-09-12 13:06 UTC, Tomerva requested changes

2021-09-12 13:06 UTC, Tomerva commented on cloudrail/knowledge/context/mergeable.py
> +class UnSupportedEntityOriginType(Exception):
rename to UnSupportedEntityOriginTypeException

2021-09-12 13:06 UTC, Tomerva commented on cloudrail/knowledge/context/mergeable.py
> +        super().__init__('origin entity type don\'t supported')
change to 'IaC type {iac_type} not supported' and pass the iac_type = self.iac_state.iac_type

2021-09-12 13:29 UTC, idan-aviv commented on cloudrail/knowledge/context/mergeable.py
> +        super().__init__('origin entity type don\'t supported')
@Tomerva the logic cause to exception is on origin entity not iac type

2021-09-13 11:54 UTC, Tomerva commented on cloudrail/knowledge/context/mergeable.py
> +        super().__init__('origin entity type don\'t supported')
@idan-aviv but the error is originated from the value of self.iac_state.iac_type

2021-09-30 09:09 UTC, Tomerva requested changes

2021-09-30 09:09 UTC, Tomerva commented on cloudrail/knowledge/context/mergeable.py
> +class UnSupportedIacType(Exception):
rename to UnSupportedIacTypeException (all our exceptions end with Exception)

2021-09-30 09:09 UTC, Tomerva commented on cloudrail/knowledge/context/mergeable.py
> +        super().__init__('IaC type don\'t supported')
IaC type not supported

2021-09-30 10:07 UTC, Tomerva approved these changes

2021-09-30 10:11 UTC, Tomerva approved these changes

2021-09-30 12:13 UTC, merged