CR-3043: Drift detection: Changing default SG for an EC2 instance is not detected
indeni/cloudrail-knowledge pull request #219
Opened 2021-09-19 11:38 UTC by Imanuel-Mizrahi

modified resource and class for EC2 instance

2021-09-26 09:39 UTC, Tomerva requested changes

2021-09-26 09:39 UTC, Tomerva commented on cloudrail/knowledge/context/aws/pseudo_builder.py
> +            subnet = ResourceInvalidator.get_by_id(subnets, ec2.raw_data.subnet_id, False)
why?

2021-09-26 09:39 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources/ec2/ec2_instance.py
> +                 security_groups_ids: List[str]):
the security groups are attached to the underlying network interface, not the actual EC2

2021-09-29 08:53 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources/ec2/ec2_instance.py
> +                 security_groups_ids: List[str]):
@Tomerva , but we agreed with @yi2020 that we should add the "security_group_ids" for the EC2 instance, as we had no other solution for drift.

2021-09-29 08:57 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/pseudo_builder.py
> +            subnet = ResourceInvalidator.get_by_id(subnets, ec2.raw_data.subnet_id, False)
@Tomerva 
When you create a simple EC2, using TF, without any networking, AWS create all the networking by it's own.
This means that the TF context will not hold the subnet of this EC2, in it's TF context.
As a result, this function will invalidate the EC2, while it is not correct.
It will be correct to invalidate it only after the merged context, but not while building the drift context.

2021-10-05 12:56 UTC, closed without merging

2021-10-05 12:56 UTC, Imanuel-Mizrahi commented
Will have a different solution once drift detection explicit will be ready, moving ticket to backlog