Feature/cr 3191 azure context cosmos db account
indeni/cloudrail-knowledge pull request #220
Opened 2021-09-23 18:56 UTC by lirshindalman

2021-09-26 09:57 UTC, Tomerva commented on cloudrail/knowledge/context/azure/resources/databases/azure_cosmos_db_account.py
> +            max_interval_in_seconds: Time amount that staleness is tolerated.
@yi2020 @oqf "Time amount"; i believe this should be rephrased

2021-09-26 10:13 UTC, Tomerva requested changes

2021-09-26 10:13 UTC, Tomerva commented on cloudrail/knowledge/context/azure/resources/databases/azure_cosmos_db_account.py
> +        return 'CosmosDB ' + 'Account' if not is_plural else 'Accounts'
if is_plural is true, this will return just 'Accounts' and not 'CosmosDB Accounts'

2021-09-26 10:13 UTC, Tomerva commented on cloudrail/knowledge/context/azure/resources_builders/scanner/cosmos_db_account_builder.py
> +            cors_rule_list.append(CosmosDBAccountCorsRule(cors_rule.get('allowedHeaders', '').split(','),
should the resulted list items be trimmed?

2021-09-29 08:56 UTC, lirshindalman commented on cloudrail/knowledge/context/azure/resources_builders/scanner/cosmos_db_account_builder.py
> +            cors_rule_list.append(CosmosDBAccountCorsRule(cors_rule.get('allowedHeaders', '').split(','),
Yes to match the data to the way it is obtained in the terraform plan

2021-09-29 10:02 UTC, Tomerva approved these changes

2021-09-29 10:05 UTC, Tomerva approved these changes

2021-09-29 17:42 UTC, merged