CR-3430: [CFN] public_access_security_groups_all_ports_rule
indeni/cloudrail-knowledge pull request #290
Opened 2021-11-02 07:07 UTC by Imanuel-Mizrahi

2021-11-02 13:56 UTC, Tomerva requested changes

2021-11-02 13:56 UTC, Tomerva commented on cloudrail/knowledge/utils/utils.py
> +    return bool(array) and all(x for x in array)
what if the array has value of False ?

2021-11-02 13:56 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources_builders/cloudformation/ec2/cloudformation_ec2_builder.py
> +            if check_array_has_value(security_groups_ids_from_resource) and all('.' not in x for x in security_groups_ids_from_resource) else None
what if not **all**, but some values have '.' ?

2021-11-02 14:40 UTC, Tomerva requested changes

2021-11-02 14:40 UTC, Tomerva commented on cloudrail/knowledge/utils/utils.py
> +def check_array_has_value(array: Union[list, set]) -> bool:
this type is too restrictive, and the name is not accurate
it should be of type Iterable, and the arg name and function name should change accordingly as well.

also please add tests for this function

(an iterable is any collection which you can **iterate** over, like run for-loops on, or for-comprehension)

2021-11-02 14:40 UTC, Tomerva commented on cloudrail/knowledge/utils/utils.py
> +    return bool(array) and all(x for x in array if not isinstance(x, bool))
if the function checks that a value exists, which im guessing for a list like [ None, None ] it should return false, i would implement it like this:

`return any[x is not None for x in iterable]`

2021-11-02 14:40 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources_builders/cloudformation/ec2/cloudformation_ec2_builder.py
> +            if check_array_has_value(security_groups_ids_from_resource) and any('.' not in x for x in security_groups_ids_from_resource) else None
where you use check_array_has_value, wouldnt you want to get only the not-None values?

2021-11-03 06:26 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources_builders/cloudformation/ec2/cloudformation_ec2_builder.py
> +            if check_array_has_value(security_groups_ids_from_resource) and any('.' not in x for x in security_groups_ids_from_resource) else None
what about the other places?

2021-11-03 06:29 UTC, Tomerva requested changes

2021-11-03 06:29 UTC, Tomerva commented on tests/unit/utils/test_list_utils.py
> +class TestListUtils(unittest.TestCase):
please rename class (and file), as its not a List util
you can rename it to like TestCheckIterableHasValue and this file will only test this function

2021-11-10 11:26 UTC, Tomerva requested changes

2021-11-10 11:26 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources_builders/cloudformation/ec2/cloudformation_ec2_builder.py
> +        security_group_ids_from_enis = set(sg for sg in security_group_ids_from_enis)
redundant list comprehension - you can just do `set(security_group_ids_from_enis)`, and you can merge this with previous line `set(flag_list .... ))`

2021-11-10 11:26 UTC, Tomerva commented on cloudrail/knowledge/utils/utils.py
> +    return bool(iterable) and any(x is not None for x in iterable)
as previously discussed, the `any` part is sufficient 
![image](https://user-images.githubusercontent.com/10116471/141104682-7f83eb11-d7aa-4065-9604-e8b266fa1d7a.png)

2021-11-10 11:26 UTC, Tomerva commented on cloudrail/knowledge/utils/utils.py
> +def check_iterable_has_value(iterable: Iterable) -> bool:
rename to is_iterable_with_values

2021-11-10 11:27 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources_builders/cloudformation/ec2/cloudformation_ec2_builder.py
> +            if check_array_has_value(security_groups_ids_from_resource) and any('.' not in x for x in security_groups_ids_from_resource) else None
@Imanuel-Mizrahi the above question still stands

2021-11-10 11:33 UTC, idan-aviv approved these changes

2021-11-10 12:04 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/utils/utils.py
> +    return bool(iterable) and any(x is not None for x in iterable)
@Tomerva , but this is not good enough for a "set", I checked it, the tests failing.

2021-11-10 12:41 UTC, Tomerva approved these changes

2021-11-10 13:37 UTC, merged