Feature/cr 2622 aws cfn test dms replication instance
indeni/cloudrail-knowledge pull request #292
Opened 2021-11-02 14:22 UTC by lirshindalman

2021-11-02 14:34 UTC, Imanuel-Mizrahi requested changes

2021-11-02 14:34 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources_builders/cloudformation/dms/dms_replication_instance_builder.py
> +        account = self.get_property(cfn_res_attr, 'account_id')
I do not think we need to "get_property" for account and region values.

2021-11-02 14:34 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources_builders/cloudformation/dms/dms_replication_instance_builder.py
> +from typing import Dict
The file name convention is: cloudformation<resource_name>_builder.py
Please rename accordingly.

2021-11-02 14:34 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources_builders/cloudformation/dms/dms_replication_instance_builder.py
> +        name = self.get_property(properties, 'ReplicationInstanceIdentifier', self.create_random_pseudo_identifier())
I think we should be able to use: "self.get_resource_id(cfn_res_attr)" as the default value in the "get_property" for the name attribute.

2021-11-02 14:34 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources_builders/cloudformation/dms/dms_replication_instance_builder.py
> +        arn = build_arn('config', region, account, 'config-aggregator/', 'config-aggregator-', self.create_random_pseudo_identifier())
There is a mess here.
This is an ARN for config aggregator, not for DMS...
Something is strange here...

2021-11-02 14:34 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources_builders/cloudformation/dms/dms_replication_instance_builder.py
> +        publicly_accessible = properties['PubliclyAccessible']
Does the attribute: "PubliclyAccessible" is a mandatory field?
Otherwise, please implement "get_property"

2021-11-02 14:34 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources_builders/cloudformation/dms/dms_replication_instance_subnet_group_builder.py
>  from cloudrail.knowledge.context.aws.resources_builders.cloudformation.base_cloudformation_builder import BaseCloudformationBuilder
1. Rename the file according to the convention, as mentioned in previous comment.
2. The parse resource function is set to return ConfigService resource, we need to change it to: DmsReplicationInstanceSubnetGroup.
These changes are unrelated to your PR, but not sure how it got there, and needs to be fixed...

2021-11-02 14:34 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/aws/aws_rules_metadata.yaml
> -    terraform: For the dms_replication_instance resource, set vpc_security_group_ids
Why was that changed? I think we should remain it as "dms_replication_instance"

2021-11-02 14:34 UTC, Imanuel-Mizrahi commented on tests/knowledge/context/aws/test_dms_replication_instance.py
> +from tests.knowledge.context.test_context_annotation import context, TestOptions
Probably we need to remove the "TestOptions" here.

2021-11-03 08:33 UTC, Imanuel-Mizrahi requested changes

2021-11-03 08:33 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources_builders/cloudformation/dms/cloudformation_dms_replication_instance_builder.py
> +        arn = build_arn('dms', region, account, 'replication-instance/', 'replication-instance-', self.create_random_pseudo_identifier())
@lirshindalman , the build_arn, should return the dms_replication_instance ARN.
You can find an example of the ARN here:
https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Introduction.AWS.ARN.html
You should probably use the "name" instead of the create_random_pseudo_identifier.
I suggest to debug, and make sure the structure is as expected.

2021-11-03 08:33 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/utils/arn_utils.py
> +    if service in ['s3', 'sns', 'apigateway', 'execute-api', 'dms']:
Are you sure we need to update here?

2021-12-30 11:31 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources_builders/scanner/cloud_mapper_component_builder.py
> +                                  subnet_group_data.get('ReplicationSubnetGroupIdentifier', 'default'),
I am a bit afraid of this change.
This means that we cannot create a replication instance without it will be attached to some subnet group, but is it so?
Please make sure this is the case.

2021-12-30 11:31 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources_builders/terraform/terraform_resource_builder_helper.py
> +                                  _get_known_value(attributes, 'replication_subnet_group_id', 'default'),
Same here.

2021-12-30 11:52 UTC, Imanuel-Mizrahi approved these changes

2021-12-30 12:41 UTC, idan-aviv commented on tests/unit/test_cloudformation_fields.py
>  import unittest
don't see any new cloudformation_resource_attributes_mapper function

2021-12-30 12:41 UTC, idan-aviv commented on tests/knowledge/context/aws/test_dms_replication_instance.py
> -    @context(module_path="default_vpc_public_access", base_scanner_data_for_iac='account-data-dms-instance-networking-public.zip')
any reason?

2021-12-30 13:22 UTC, merged