compute instance no public ip rule
indeni/cloudrail-knowledge pull request #298
Opened 2021-11-10 14:09 UTC by doronafota

2021-11-15 07:57 UTC, Imanuel-Mizrahi requested changes

2021-11-15 07:57 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/gcp/non_context_aware/compute_instance_no_public_ip_rule.py
> +                                compute_instance,
I had something similar in my rule lately.
I am not sure we need the evidence string to alert about the TF structure, but on the actual meaning.
Please advise with satya how to make the evidence more generic. 
Something like: 
"The {compute_instance.get_type()} `{compute_instance.get_friendly_name()}` has interfaces with public ip" 
@idan-aviv @Tomerva , what do you think?

2021-11-15 13:54 UTC, Tomerva commented on cloudrail/knowledge/rules/gcp/non_context_aware/compute_instance_no_public_ip_rule.py
> +                                compute_instance,
yes, in general evidence should not talk about blocks. thats the remediation step's job

2021-11-15 13:54 UTC, Tomerva approved these changes

2021-11-15 16:07 UTC, idan-aviv commented on cloudrail/knowledge/rules/gcp/non_context_aware/compute_instance_no_public_ip_rule.py
> +            if network_interfaces_list := compute_instance.network_interfaces:
@doronafota redundant if condition

2021-11-15 16:14 UTC, idan-aviv commented on tests/knowledge/rules/gcp/non_context_aware/test_compute_instance_no_public_ip_rule.py
> +        compute_instance_2 = create_empty_entity(GcpComputeInstance)
@doronafota can you please explain the meaning of this condition?

2021-11-15 16:15 UTC, idan-aviv commented on tests/knowledge/rules/gcp/non_context_aware/test_compute_instance_no_public_ip_rule.py
> +        if should_alert:
@doronafota can remove this condition and add 'total_issues' and 'rule_status' params

2021-11-16 18:11 UTC, doronafota commented on cloudrail/knowledge/rules/gcp/non_context_aware/compute_instance_no_public_ip_rule.py
> +            if network_interfaces_list := compute_instance.network_interfaces:
compute_instance.network_interfaces is optional attribute so if it will be None and i remove the if condition i can get exception.

2021-11-17 08:17 UTC, Tomerva requested changes

2021-11-17 08:17 UTC, Tomerva commented on cloudrail/knowledge/rules/gcp/non_context_aware/compute_instance_no_public_ip_rule.py
> +            if network_interfaces_list := compute_instance.network_interfaces:
then just do `if compute_instance.network_interfaces`
another way, which also reduce nesting, is removing this condition entirely and in the for loop:
`for network_interface in compute_instance.network_interfaces or []`

by the way, how come network_interfaces is optional? can there be a compute instance (a VM?) that has no network interface? i find that odd..

2021-11-17 08:17 UTC, Tomerva commented on cloudrail/knowledge/rules/gcp/non_context_aware/compute_instance_no_public_ip_rule.py
> +                                compute_instance,
i think the evidence should be ' ... **h**as public ip address attached

2021-11-17 08:22 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/gcp/non_context_aware/compute_instance_no_public_ip_rule.py
> +            if network_interfaces_list := compute_instance.network_interfaces:
@doronafota , seems like Tomer is right, according to [TF docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#network_interface), network_interface is a required field.
The context ticket got me confused while creating the resource, I will fix it in another PR, not this one.

2021-11-17 08:26 UTC, doronafota commented on cloudrail/knowledge/rules/gcp/non_context_aware/compute_instance_no_public_ip_rule.py
> +            if network_interfaces_list := compute_instance.network_interfaces:
@Imanuel-Mizrahi do you built this resource? do you know if the network_interfaces is actually optional as written ?

2021-11-17 08:32 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/gcp/non_context_aware/compute_instance_no_public_ip_rule.py
> +            if network_interfaces_list := compute_instance.network_interfaces:
@doronafota , yes, I built it, and as mentioned in my previous comment, Tomer is right.
Do not change anything in the resource itself in this PR, I will do it in another one.

2021-11-17 08:41 UTC, idan-aviv approved these changes

2021-11-17 08:42 UTC, Imanuel-Mizrahi approved these changes

2021-11-18 06:08 UTC, Tomerva approved these changes

2021-11-18 07:09 UTC, merged