CR-2791: [Not CAR] [GCP] Ensure that instances are not configured to use the default service account
indeni/cloudrail-knowledge pull request #300
Opened 2021-11-11 09:56 UTC by Imanuel-Mizrahi

2021-11-11 14:22 UTC, Tomerva requested changes

2021-11-11 14:22 UTC, Tomerva commented on tests/knowledge/context/gcp/test_compute_instance.py
> +        self.assertTrue(len(ctx.compute_instances), 2)
why are there 2 instances but only assertion on one of them?

2021-11-11 14:22 UTC, Tomerva commented on tests/knowledge/rules/gcp/non_context_aware/test_compute_instance_do_not_use_default_service_account_rule.py
> +            ["default_service_account_used", '37924132841-compute@developer.gserviceaccount.com', True,],
redundant comma at the end

2021-11-11 15:01 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/gcp/non_context_aware/compute_instance_do_not_use_default_service_account_rule.py
> +                        f"attributes email uses default service account [project_number]-compute@developer.gserviceaccount.com",
@Tomerva , is that better:
f"The {compute_instance.get_type()} `{compute_instance.get_friendly_name()}` has service_account block "
                        f"email attribute which uses default service account [project_number]-compute@developer.gserviceaccount.com",
                        ?

2021-11-11 15:02 UTC, Imanuel-Mizrahi commented on tests/knowledge/context/gcp/test_compute_instance.py
> +        self.assertTrue(len(ctx.compute_instances), 2)
Well, the second is pretty much the same, just the name differs.
I can do it if you would like

2021-11-14 07:30 UTC, Imanuel-Mizrahi commented on tests/knowledge/context/gcp/test_compute_instance.py
> +        self.assertTrue(len(ctx.compute_instances), 2)
@Tomerva , changed that into a "for" loop, to run on both

2021-11-14 18:16 UTC, Tomerva approved these changes

2021-11-14 18:16 UTC, Tomerva commented on cloudrail/knowledge/context/base_context_builders/base_terraform_builder.py
> +                if isinstance(attributes.get(tag_key), list):
change to elif

2021-11-14 18:16 UTC, Tomerva commented on cloudrail/knowledge/utils/tags_utils.py
> +def _hash_gcp_tags_dict(dictionary: dict, salt: str) -> dict:
rename to _hash_gcp_labels_dict

2021-11-14 18:16 UTC, Tomerva commented on cloudrail/knowledge/utils/tags_utils.py
> +    gcp_raw_tags = raw_gcp_data.get('labels')
rename to gcp_raw_labels

2021-11-15 05:55 UTC, merged