sql instance backup configuration enabled rule
indeni/cloudrail-knowledge pull request #302
Opened 2021-11-11 16:14 UTC by doronafota

2021-11-14 07:05 UTC, Imanuel-Mizrahi requested changes
@doronafota , please merge your branch with the latest main, in order to make sure your changes does not impact the drifts

2021-11-14 07:05 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/gcp/non_context_aware/sql_database_instance_backup_configuration_enabled_rule.py
> +                        f"The Google Cloud database instance {sql_db_instance.get_type()} `{sql_db_instance.get_friendly_name()}` has backup_configured enabled flag not set.",
The "get_type" should return the "Google cloud database instance" so it sounds like this is duplicate...
Please check this

2021-11-14 07:44 UTC, Imanuel-Mizrahi approved these changes

2021-11-14 12:00 UTC, idan-aviv commented on cloudrail/knowledge/context/gcp/resources_builders/terraform/sql_database_instance_builder.py
> -            expiration_time = datetime.strptime(expiration_time_str, '%Y-%m-%dT%H:%M:%S')
same as above

2021-11-14 12:00 UTC, idan-aviv commented on cloudrail/knowledge/context/gcp/resources_builders/terraform/sql_database_instance_builder.py
> -                                   for authorized_network in authorized_networks_list] if authorized_networks_list else None
same as above

2021-11-14 16:04 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/gcp/non_context_aware/sql_database_instance_backup_configuration_enabled_rule.py
> +        for sql_db_instance in env_context.sql_database_instances:
But @idan-aviv , following @doronafota latest changed in this PR, "settings" will never be empty.

2021-11-14 16:04 UTC, Imanuel-Mizrahi approved these changes

2021-11-15 07:47 UTC, idan-aviv approved these changes

2021-11-15 08:18 UTC, doronafota commented on cloudrail/knowledge/rules/gcp/non_context_aware/sql_database_instance_backup_configuration_enabled_rule.py
> +        for sql_db_instance in env_context.sql_database_instances:
added checking if settings is not none

2021-11-15 08:36 UTC, merged