Feature/cr 2810 gcp db auth rule
indeni/cloudrail-knowledge pull request #306
Opened 2021-11-14 12:04 UTC by idan-aviv

2021-11-14 12:31 UTC, Imanuel-Mizrahi requested changes

2021-11-14 12:31 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/gcp/gcp_rules_metadata.yaml
> +      console: Follow the guide at https://cloud.google.com/sql/docs/sqlserver/flags  in order to ensure that
Please put <> brackets surrounding the URL link

2021-11-14 12:31 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/gcp/non_context_aware/sql_database_authentication_disable_rule.py
> +                        f"The Google Cloud database instance `{sql_db.get_friendly_name()}` "
We need to use: "get_type()" at the beginning of the evidence strihg

2021-11-14 13:49 UTC, doronafota commented on cloudrail/knowledge/rules/gcp/non_context_aware/sql_database_authentication_disable_rule.py
> +                        f"The Google Cloud database instance `{sql_db.get_friendly_name()}` "
you required to check if the 'contained database authentication' is off and your function is_flag_on checks only if it is 'on'. maybe change the function to get another parameter if the flag need to be 'on' or 'off'

2021-11-14 13:49 UTC, doronafota commented on cloudrail/knowledge/rules/gcp/non_context_aware/sql_database_authentication_disable_rule.py
> +        return bool(environment_context.sql_database_instances)
should_run_rule function is not the same with every flag?

2021-11-15 07:40 UTC, idan-aviv commented on cloudrail/knowledge/rules/gcp/non_context_aware/sql_database_authentication_disable_rule.py
> +                        f"The Google Cloud database instance `{sql_db.get_friendly_name()}` "
@Imanuel-Mizrahi can you show me where it should be in the sentence?

2021-11-15 07:43 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/gcp/non_context_aware/sql_database_authentication_disable_rule.py
> +                        f"The Google Cloud database instance `{sql_db.get_friendly_name()}` "
@idan-aviv 
It should be like this:
f"The Google Cloud {sql_db.get_type()} `{sql_db.get_friendly_name()}` " ...

2021-11-15 08:35 UTC, doronafota approved these changes

2021-11-15 08:37 UTC, Imanuel-Mizrahi approved these changes

2021-11-15 08:39 UTC, merged