Feature/cr 3575 gcp context compute global forwarding rule
indeni/cloudrail-knowledge pull request #311
Opened 2021-11-15 15:17 UTC by lirshindalman

2021-11-15 15:25 UTC, Imanuel-Mizrahi approved these changes

2021-11-15 15:25 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_global_forwarding_rule.py
> +
@lirshindalman please add: "is_labeled", as far as I see in [TF docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_global_forwarding_rule#labels), this resource could have labels (using beta provider for now.)

2021-11-15 16:39 UTC, Imanuel-Mizrahi commented
@Tomerva , should we test the "labels" / "tags" fields in the context test for every resource which could have labels/tags?

2021-11-16 07:55 UTC, Tomerva requested changes

2021-11-16 07:55 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/gcp_environment_context.py
> +        self.compute_global_forwarding_rule: List[GcpComputeGlobalForwardingRule] = compute_global_forwarding_rule or []
a resource with a unique id should be in an AliasesDict

2021-11-16 07:55 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_global_forwarding_rule.py
> +    def get_id(self) -> str:
is the name unique across projects?

2021-11-16 07:55 UTC, Tomerva commented on tests/knowledge/context/gcp/test_compute_global_forwarding_rule.py
> +    @context(module_path="basic", test_options=TestOptions(run_drift_detection=False, run_terraform=False))
why no terraform and drift tests?

2021-11-16 07:55 UTC, Tomerva commented on tests/knowledge/context/gcp/test_compute_global_forwarding_rule.py
> +        self.assertTrue(compute.target in ['google_compute_global_forwarding_rule.https-forwarding.target', 'https://www.googleapis.com/compute/v1/projects/dev-for-tests/global/targetHttpsProxies/tes
i dont understand this check

2021-11-16 09:05 UTC, Tomerva approved these changes

2021-11-16 09:06 UTC, Tomerva approved these changes

2021-11-16 09:21 UTC, merged