Feature/cr 2808 log min duration statement
indeni/cloudrail-knowledge pull request #314
Opened 2021-11-16 12:30 UTC by idan-aviv

2021-11-16 15:39 UTC, Imanuel-Mizrahi requested changes

2021-11-16 15:39 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/gcp/non_context_aware/sql_log_min_duration_disable_rule.py
> +                        f"`log_min_duration_statement` set to -1.",
@idan-aviv , something is a bit strange in this rule, the condition check we do not have value of '-1' and the alert says we have the flag set to '-1'....

2021-11-16 15:56 UTC, Tomerva commented on cloudrail/knowledge/rules/gcp/non_context_aware/postgres_database_temp_log_files_zero_rule.py
> +                        f" flag `log_temp_files` set other than 0.",
this phrasing is not good.. maybe ' .... set to something other than 0' ?
i would be more comfortable with having someone else rephrase it..

2021-11-17 07:45 UTC, Imanuel-Mizrahi approved these changes

2021-11-17 08:52 UTC, merged