CR-2772-Not_CAR-GCP-Ensure_that_IP_forwarding_is_not_enabled_on_Insta…
indeni/cloudrail-knowledge pull request #315
Opened 2021-11-16 13:29 UTC by lirshindalman

…nces

2021-11-16 15:45 UTC, Imanuel-Mizrahi requested changes

2021-11-16 15:45 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/gcp/non_context_aware/compute_instance_ensure_no_ip_forwarding_rule.py
> +                        f"The {compute_instance.get_type()} `{compute_instance.get_friendly_name()}` has attribute can_ip_forward set to true.",
I would change the evidence string, to something more generic, and not fixed for TF.
Perhaps:
"The {compute_instance.get_type()} `{compute_instance.get_friendly_name()}` has IP forwarding feature enabled."
@lirshindalman , please advise with Satya about possible syntax.

2021-11-16 15:45 UTC, Imanuel-Mizrahi commented on tests/knowledge/rules/gcp/non_context_aware/test_compute_instance_ensure_no_ip_forwarding_rule.py
> +    def test_compute_instance_default_service_account_usage(self, unused_name: str, can_ip_forward: bool, should_alert: bool):
Please change the test name

2021-11-17 07:46 UTC, Imanuel-Mizrahi approved these changes

2021-11-17 14:04 UTC, Tomerva approved these changes

2021-11-17 14:04 UTC, merged