BaseRuleTest: assert evidence
indeni/cloudrail-knowledge pull request #317
Opened 2021-11-17 12:21 UTC by idan-aviv

2021-11-21 08:33 UTC, Tomerva commented on tests/knowledge/rules/base_rule_test.py
> +        self.assertRegexpMatches(evidence_str, r'^[A-Za-z0-9-_#?:\'".,\s`~/\\()\[\]*{}\$]+$', '')
what does the regex search for?

2021-11-21 13:16 UTC, Viperain requested changes

2021-11-21 13:16 UTC, Viperain commented on tests/knowledge/rules/base_rule_test.py
> +            self._assert_evidence(rule_result.issues[0].evidence)
go over all rule_result.issues not only the first one

2021-11-22 08:30 UTC, idan-aviv commented on tests/knowledge/rules/base_rule_test.py
> +        self.assertRegexpMatches(evidence_str, r'^[A-Za-z0-9-_#?:\'".,\s`~/\\()\[\]*{}\$]+$', '')
@Tomerva invalid char in evidence string

2021-11-22 13:07 UTC, idan-aviv commented on tests/knowledge/rules/base_rule_test.py
> +            self._assert_evidence(rule_result.issues[0].evidence)
NP but the evidence is the same! (besides friendly names)

2021-11-23 09:05 UTC, Tomerva approved these changes

2021-11-23 09:36 UTC, Viperain approved these changes

2021-11-23 09:37 UTC, merged