CR-3586-Drift-google_compute_firewall-change_firewall_rules
indeni/cloudrail-knowledge pull request #319
Opened 2021-11-18 09:29 UTC by lirshindalman

2021-11-18 09:33 UTC, Imanuel-Mizrahi approved these changes

2021-11-18 09:44 UTC, Tomerva requested changes

2021-11-18 09:44 UTC, Tomerva commented on tests/knowledge/context/drift/base_drift_test.py
> +        return None
should return the project id

2021-11-23 08:26 UTC, Tomerva approved these changes

2021-11-23 08:26 UTC, Tomerva commented on cloudrail/knowledge/utils/utils.py
> +def get_project_id(account_data_dir: str) -> str:
change to get_gcp_project_id so it will be clearer

2021-11-23 09:31 UTC, merged