Cr 2117 no unusued security group rule adding new resources
indeni/cloudrail-knowledge pull request #32
Opened 2021-05-20 10:24 UTC by Imanuel-Mizrahi

2021-05-24 06:50 UTC, Tomerva requested changes

2021-05-24 06:52 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/apigatewayv2/api_gateway_v2.py
> +class ApiGateway(NetworkEntity):
@Tomerva , these are not exactly the same.
This is api_gw_v2 (API GW for HTTP and Socket), and the other is rest API, so I do not think we need to have the same naming

2021-05-24 06:58 UTC, Tomerva approved these changes

2021-05-24 13:56 UTC, yi2020 requested changes

2021-05-24 15:01 UTC, Imanuel-Mizrahi commented
@yi2020 , modified as requested, please review.
Thanks!

2021-05-25 19:58 UTC, yi2020 approved these changes

2021-05-26 05:25 UTC, merged