TestComputeInstance: new GCP DD test class
indeni/cloudrail-knowledge pull request #320
Opened 2021-11-18 11:53 UTC by idan-aviv

2021-11-18 13:34 UTC, Tomerva requested changes

2021-11-18 13:34 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_instance.py
> +class GcpComputeInstanceServiceAcount(DriftDetectionResource):
missing c in 'Account'

2021-11-18 13:45 UTC, Imanuel-Mizrahi approved these changes

2021-11-20 20:36 UTC, Tomerva approved these changes

2021-11-21 08:27 UTC, merged