Feature/cr 3490 storage bucket
indeni/cloudrail-knowledge pull request #329
Opened 2021-11-22 12:32 UTC by idan-aviv

2021-11-22 13:55 UTC, Imanuel-Mizrahi requested changes

2021-11-22 13:55 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/gcp/resources/storage/gcp_storage_bucket.py
> +            uniform_bucket_level_access: ((Optional, Default = false) Enables Uniform bucket-level access access to a bucket.
remove one bracket '(' sign

2021-11-22 13:55 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/gcp/resources/storage/gcp_storage_bucket.py
> +        return [self.name]
@idan-aviv , are you sure bucket name is unique in all projects?
I am not sure, because the URL includes the project_id, and you have a "region" for the bucket, so potentially, you could have the same name in different regions?
I see that the region is a required field for TF, so perhaps the get_keys should be: "[self.name, self.project_id, self.region]"?

2021-11-22 13:55 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/gcp/resources/storage/gcp_storage_bucket.py
> +    def get_id(self) -> str:
I think this should be "get_name"

2021-11-22 14:44 UTC, idan-aviv commented on cloudrail/knowledge/context/gcp/resources/storage/gcp_storage_bucket.py
> +        return [self.name]
@Imanuel-Mizrahi bucket name must be globally unique

2021-11-22 14:46 UTC, idan-aviv commented on cloudrail/knowledge/context/gcp/resources/storage/gcp_storage_bucket.py
> +    def get_id(self) -> str:
@Imanuel-Mizrahi id can be bucket name cause it is globally unique name

2021-11-22 15:26 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/gcp/resources/storage/gcp_storage_bucket.py
> +        return [self.name]
@idan-aviv , you are [right](https://cloud.google.com/storage/docs/naming-buckets)!
Thanks!

2021-11-22 15:26 UTC, Imanuel-Mizrahi approved these changes

2021-11-23 07:12 UTC, Tomerva requested changes

2021-11-23 07:12 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources/storage/gcp_storage_bucket.py
> +        self.with_aliases(name)
the name is globally unique?

2021-11-23 07:12 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources/storage/gcp_storage_bucket.py
> +class GcpStorageBucket(GcpResource):
add get_name implementation

2021-11-23 07:12 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources/storage/gcp_storage_bucket.py
> +    def to_drift_detection_object(self) -> dict:
why is this empty?

2021-11-23 08:47 UTC, idan-aviv commented on cloudrail/knowledge/context/gcp/resources/storage/gcp_storage_bucket.py
> +        self.with_aliases(name)
@Tomerva yes

2021-11-23 08:50 UTC, idan-aviv commented on cloudrail/knowledge/context/gcp/resources/storage/gcp_storage_bucket.py
> +    def to_drift_detection_object(self) -> dict:
@Tomerva cause you can't edit any of the bucket attributes without re-creating the object...

2021-11-23 09:13 UTC, Tomerva approved these changes

2021-11-23 09:54 UTC, merged