CR-3619: [GCP] [Context] DNS Managed Zone
indeni/cloudrail-knowledge pull request #334
Opened 2021-11-28 09:14 UTC by Imanuel-Mizrahi

added resource builders and tests

2021-11-28 11:28 UTC, Tomerva requested changes

2021-11-28 11:28 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources_builders/scanner/dns_managed_zone_builder.py
> +        dnssec_config = None
redundant line

2021-11-28 11:28 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources_builders/terraform/dns_managed_zone_builder.py
> +        dnssec_config = None
redundant line

2021-11-28 11:28 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources_builders/terraform/dns_managed_zone_builder.py
> +                for default_key_specs_data in self._get_known_value(dnssec_config_data[0], 'default_key_specs', []):
isnt the default value here redundant?

also i would declare a variable for `self._get_known_value(dnssec_config_data[0], 'default_key_specs')`

2021-11-28 11:28 UTC, Tomerva commented on cloudrail/knowledge/rules/gcp/non_context_aware/cloud_dns_no_rsasha1_used_rules.py
> +                and any(default_key.algorithm == DnsDefKeyAlgorithm.RSASHA1 for default_key in cloud_dns.dnssec_config.default_key_specs):
please fix indentation. also if you put the `and` at the end of the line it will be easier to indent

2021-11-28 11:28 UTC, Tomerva commented on tests/knowledge/context/gcp/test_dns_managed_zone.py
> +            if default_key.key_type == DnsDefKeyType.ZONESIGNING:
i dont like having these conditions in tests. the test should be deterministic. i assume there are 2 keys in default_key_specs right? then you should get them in a deterministic way and then assert on each of them separately

2021-11-28 19:09 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/gcp/resources_builders/terraform/dns_managed_zone_builder.py
> +        dnssec_config = None
@Tomerva , not sure why this is redundant. I am starting by assigning a default (None) value for the variable: "dnssec_config", as it's not a mandatory field.
Perhaps you suggest I will assign this default value in the actual resource class instead?

2021-11-28 19:22 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/gcp/resources_builders/terraform/dns_managed_zone_builder.py
> +                for default_key_specs_data in self._get_known_value(dnssec_config_data[0], 'default_key_specs', []):
Well, almost.
If you do not specify **anything**, you will have automatically 2 keys defined, with the variables I set at the "extend" (note there is a different key_type in each key).
So, I set these as the default keys, if nothing else is specified.

2021-11-28 19:28 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/gcp/non_context_aware/cloud_dns_no_rsasha1_used_rules.py
> +                and any(default_key.algorithm == DnsDefKeyAlgorithm.RSASHA1 for default_key in cloud_dns.dnssec_config.default_key_specs):
Fixed, hopefully

2021-11-28 19:29 UTC, Imanuel-Mizrahi commented on tests/knowledge/context/gcp/test_dns_managed_zone.py
> +            if default_key.key_type == DnsDefKeyType.ZONESIGNING:
yes, the default_key_specs must always contain 2 keys.
I tried to fix it, hope this is what you meant.
Please review.

2021-11-29 07:01 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources_builders/terraform/dns_managed_zone_builder.py
> +                for default_key_specs_data in self._get_known_value(dnssec_config_data[0], 'default_key_specs', []):
im talking about line 20.. you already check the boolean value of `self._get_known_value(dnssec_config_data[0], 'default_key_specs')` in the if, so in the else it must already have a value

2021-11-29 07:02 UTC, Tomerva commented on cloudrail/knowledge/rules/gcp/non_context_aware/cloud_dns_no_rsasha1_used_rules.py
> +                and any(default_key.algorithm == DnsDefKeyAlgorithm.RSASHA1 for default_key in cloud_dns.dnssec_config.default_key_specs):
it looks the same..

2021-11-29 07:04 UTC, Tomerva requested changes

2021-11-29 07:04 UTC, Tomerva commented on tests/knowledge/context/gcp/test_dns_managed_zone.py
> +            if default_key.key_type == DnsDefKeyType.ZONESIGNING:
the if/else i would remove from the for loop, and assert i have one key with `DnsDefKeyType.ZONESIGNING` with the correct algorithm, and do same assertion for the other key

2021-11-29 07:18 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/gcp/resources_builders/terraform/dns_managed_zone_builder.py
> +                for default_key_specs_data in self._get_known_value(dnssec_config_data[0], 'default_key_specs', []):
OK, this one was changed already, please check the files itself.

2021-11-29 07:20 UTC, Imanuel-Mizrahi commented on tests/knowledge/context/gcp/test_dns_managed_zone.py
> +            if default_key.key_type == DnsDefKeyType.ZONESIGNING:
This is pretty much what I did, please re-check the file

2021-11-29 07:33 UTC, Tomerva approved these changes

2021-11-29 07:46 UTC, merged