Cr 3452 compute target ssl proxy
indeni/cloudrail-knowledge pull request #336
Opened 2021-11-28 15:15 UTC by doronafota

2021-11-28 19:03 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_ssl_proxy.py
> +    def get_id(self) -> str:
Another general note: sounds like you added a few implementations for "get_id()", and if so, you may be able to change this resource to "AliasesDict".

2021-11-29 10:17 UTC, Tomerva requested changes

2021-11-29 10:17 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/gcp_relations_assigner.py
> +    def _assign_ssl_policy(target_ssl_proxy: GcpComputeTargetSslProxy, ssl_policies: List[GcpComputeSslPolicy]):
this function should be more generic - it refers to two entities (and i guess it will refer to more in the future), ssl proxy and https proxy, but the function signature refers only to ssl proxy only
so there are 2 valid options:
1. create some interface (abstract class in python) that both `GcpComputeTargetSslProxy` and `GcpComputeTargetHttpsProxy` use, that will contains an ssl_policy attribute.
2. add an additional parameter, that is a function that assigns the found ssl_policy to the object

i think #1 would be better in the long run because i assume there will be rules that will check the ssl policy of resources regardless of these resource's types. but other than that, #2 is an easier solution that doesnt complicate things

2021-11-29 10:17 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/gcp_relations_assigner.py
> +        if not global_forwarding_rule.target_obj:
its possible that there will already be a value here?

2021-11-29 10:17 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/gcp_relations_assigner.py
> +        if not target_ssl_proxy.ssl_policy_obj:
its possible that there will already be a value here?

2021-11-29 10:17 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_ssl_policy.py
> +        return [self.self_link, self.policy_id, self.name, self.project_id]
i agree get_keys should be the minimum required to identify a resource. usually name+project-id is enough, but also self_link alone is mostly also enough. in this particular case, maybe policy_id is also enough (is it globally unique?)
but either way, make sure the value you get from TF is the same as from live env.

if policy_id is globally unique, i think it would be the safest option.

2021-11-29 10:17 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_ssl_policy.py
> +        return self.policy_id
if policy_id is globally unique, then the collection of GcpComputeSslPolicy should be AliasesDict

2021-11-29 10:17 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_ssl_policy.py
> +        self.self_link: str = self_link
should probably add self_link as an alias, if other resources can identify this resource by that self_link

2021-11-29 10:17 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_http_proxy.py
> +            target_id: an identifier for the resource with format projects/{{project}}/global/targetHttpProxies/{{name}}
target_id is the target's self_link?

2021-11-29 10:17 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_https_proxy.py
> +        self.ssl_policy_obj: Optional[GcpComputeTargetProxy] = None
the actual object should be called `ssl_policy`, and the identifier (the current ssl_policy) should be renamed to something more descriptive. is it ssl_policy_self_link? ssl_policy_id? ..

2021-11-29 10:17 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_proxy.py
> +
remove 1 empty line

2021-11-29 10:17 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_proxy.py
> +            name: (Required) A unique name of the resource.
missing self_link

2021-11-29 10:17 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_proxy.py
> +    def __init__(self,
maybe it would be better to add target type? (ssl, http, https)

2021-11-29 10:17 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_ssl_proxy.py
> +        return [self.target_id, self.self_link, self.project_id]
same comment as before about get_keys

2021-11-29 10:17 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_ssl_proxy.py
> +    def get_id(self) -> str:
if target_id is globally unique, it should be aliases dict

2021-11-29 10:17 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_ssl_proxy.py
> +        return {}
missing drift fields

2021-11-29 10:49 UTC, doronafota commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_ssl_policy.py
> +        return [self.self_link, self.policy_id, self.name, self.project_id]
policy_id format is - projects/{{project}}/global/sslPolicies/{{name}} so i think is globally unique

i will use it for get_keys()

2021-11-29 10:50 UTC, doronafota commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_ssl_proxy.py
> +    def get_id(self) -> str:
same as above

2021-11-29 10:55 UTC, doronafota commented on cloudrail/knowledge/context/gcp/gcp_relations_assigner.py
> +    def _assign_ssl_policy(target_ssl_proxy: GcpComputeTargetSslProxy, ssl_policies: List[GcpComputeSslPolicy]):
I implement is_encrypted property - this is a good solution?
look in my last changes

2021-11-29 10:57 UTC, doronafota commented on cloudrail/knowledge/context/gcp/gcp_relations_assigner.py
> +        if not global_forwarding_rule.target_obj:
target_proxy.ssl_policy_obj contain only 1 target and the function tun for all the targets types so when I find the target I don't want to override the target with None value

2021-11-29 10:58 UTC, doronafota commented on cloudrail/knowledge/context/gcp/gcp_relations_assigner.py
> +        if not target_ssl_proxy.ssl_policy_obj:
same as above

2021-11-29 10:58 UTC, doronafota commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_ssl_policy.py
> +        return self.policy_id
policy_id is globally unique i will use it

2021-11-29 10:59 UTC, doronafota commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_proxy.py
> +            name: (Required) A unique name of the resource.
added

2021-11-29 11:51 UTC, doronafota commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_proxy.py
> +    def __init__(self,
added

2021-11-29 11:52 UTC, doronafota commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_ssl_proxy.py
> +        return {}
added

2021-11-29 11:58 UTC, Imanuel-Mizrahi approved these changes

2021-11-29 11:58 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_proxy.py
> +        """
I guess this should be under "is_encrypted"

2021-11-29 12:01 UTC, Tomerva requested changes

2021-11-29 12:01 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_ssl_proxy.py
> +        return {"ssl_certificates": self.ssl_certificates,
i would add ssl policy

2021-11-30 09:23 UTC, doronafota commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_http_proxy.py
> +            target_id: an identifier for the resource with format projects/{{project}}/global/targetHttpProxies/{{name}}
no it's two different fields

2021-11-30 09:57 UTC, doronafota commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_https_proxy.py
> +        self.ssl_policy_obj: Optional[GcpComputeTargetProxy] = None
changed

2021-11-30 09:58 UTC, doronafota commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_proxy.py
> +
removed

2021-11-30 11:01 UTC, Tomerva requested changes

2021-11-30 11:01 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_target_ssl_proxy.py
> +        return {"ssl_certificates": self.ssl_certificates,
add the ssl policy identifier

2021-11-30 12:40 UTC, Tomerva requested changes

2021-11-30 12:40 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/gcp_relations_assigner.py
> +            global_forwarding_rule.add_invalidation("Could not associate target proxy")
the invalidation should be done in the get_by_logic method, look at the parameters it takes

2021-11-30 12:59 UTC, Tomerva approved these changes

2021-11-30 14:15 UTC, merged