compute subnetwork change cidr drift test
indeni/cloudrail-knowledge pull request #350
Opened 2021-12-07 09:14 UTC by doronafota

2021-12-07 12:51 UTC, Imanuel-Mizrahi requested changes

2021-12-07 12:51 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/gcp/resources/compute/gcp_compute_subnetwork.py
> +        enable: (Optional) true if flow logs is enable else false
I would rename the field to "enabled".
and the doc string to:
enabled: Indication if the flow logs are enabled or not.

2021-12-07 12:51 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/gcp/non_context_aware/compute_subnetwork_enable_flow_logs_rule.py
> +            if not subnetwork.name == 'default' and not subnetwork.log_config.enable:
I would change the condition to be positive :-)
if subnetwork.name != 'default' and ...

2021-12-07 15:23 UTC, Imanuel-Mizrahi approved these changes

2021-12-12 11:07 UTC, Viperain approved these changes

2021-12-12 11:27 UTC, merged