CR-3493: [GCP] [Context] Storage Bucket IAM
indeni/cloudrail-knowledge pull request #353
Opened 2021-12-08 12:26 UTC by Imanuel-Mizrahi

added builders and tests

2021-12-19 15:25 UTC, Tomerva requested changes

2021-12-19 15:25 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/gcp_iam_actions.py
> +            role_members_map.update({role: role_members})
why update and not role_members_map[role] = role_members:

2021-12-19 15:25 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/gcp_iam_actions.py
> +    def merge_iam_policies(cls, iam_policies: List[IamAccessPolicy]):
add return type

2021-12-19 15:25 UTC, Tomerva commented on cloudrail/knowledge/context/gcp/resources_builders/terraform/iam_policy_builder.py
> +        if len(policies_types) > 1 and GcpIamPolicyType.AUTHORITATIVE in policies_types:
performance wise it would be better if you would remove line 44 and then in line 45 do this:
`if any(policy.policy_type == GcpIamPolicyType.AUTHORITATIVE  for policy in iam_policies)`

2021-12-19 19:02 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/gcp/resources_builders/terraform/iam_policy_builder.py
> +        if len(policies_types) > 1 and GcpIamPolicyType.AUTHORITATIVE in policies_types:
But this condition is not true.
What I wanted to check is:
1. We have more than **one** type of policy.
2. One of the types is "AUTHORITATIVE"
Using your suggested code, I will crash even if I will have only AUTHORITATIVE type.

2021-12-19 19:03 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/gcp/gcp_iam_actions.py
> +            value = cls.merge_bindings(value)
Once I do that, I encounter issues with the drift mechanism.
The list of bindings has different order, so the comparison of the object got screwed = it reports about drifts, which are not actual drifts, just the order is different.

2021-12-20 07:54 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/gcp/gcp_iam_actions.py
> +            value = cls.merge_bindings(value)
Found the issue, fixed

2021-12-20 07:58 UTC, Tomerva approved these changes

2021-12-20 08:12 UTC, merged