Ensure that Activity Log Alert exists for Network Security Group Rule…
indeni/cloudrail-knowledge pull request #361
Opened 2021-12-19 13:22 UTC by doronafota

…s events

2021-12-19 15:58 UTC, Tomerva requested changes

2021-12-19 15:58 UTC, Tomerva commented on cloudrail/knowledge/context/azure/azure_relations_assigner.py
> +        # def create_monitor_activity_alert_log_map():
remove comments

2021-12-19 15:58 UTC, Tomerva commented on cloudrail/knowledge/rules/azure/non_context_aware/monitor_activity_log_alert_exists_rule.py
> +                            f"The {monitor.get_type()} `{monitor.get_friendly_name()}` on '{subscription.subscription_id}' does not enabled",
should change to "...is not enabled"

2021-12-20 07:10 UTC, Imanuel-Mizrahi approved these changes

2021-12-20 07:56 UTC, Tomerva approved these changes

2021-12-20 09:29 UTC, merged