Cr 3692 azure context postgre sql server
indeni/cloudrail-knowledge pull request #368
Opened 2021-12-21 13:28 UTC by lirshindalman

2021-12-22 13:57 UTC, Imanuel-Mizrahi requested changes

2021-12-22 13:57 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/azure_environment_context.py
> +    AzurePostgreSqlServerConfiguration
I think that "AzurePostgreSqlServerConfiguration" should be imported from it's own file, currently it's being imported from the same file as "AzurePostgreSqlServer"

2021-12-22 13:57 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/azure_relations_assigner.py
> +        postgresql_server_configs = ResourceInvalidator.get_by_logic(
probably line 113 could be removed, and we can just put here:
"postgresql_server.postgresql_configuration = ResourceInvalidator.get_by_logic( ..."

2021-12-22 13:57 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources/databases/azure_postgresql_server.py
> +                 tags: Dict[str, str] = None):
remove "tags" it's not needed in Azure resources, we collect it automatically in the builders.
Did you make sure that all fields which are "Optional" are indeed Optional? Each one of them might be None in some cases?

2021-12-22 13:57 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources/databases/azure_postgresql_server.py
> +        if tags:
remove tags

2021-12-22 13:57 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources/databases/azure_postgresql_server.py
> +        return {'tags': self.tags,
Should we add more fields here?
Are there anything else the user might change without re-creating the resource?

2021-12-22 13:57 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources_builders/scanner/postgresql_server_builder.py
> +                                     tags=attributes.get('tags'))
remove tags

2021-12-22 13:57 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources_builders/terraform/postgresql_server_builder.py
> +                                     tags=self._get_known_value(attributes, 'tags'))
remove tags

2021-12-22 13:57 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/terraform/azure_terraform_fields.yaml
> +      - tags:
remove tags

2021-12-22 13:57 UTC, Imanuel-Mizrahi commented on tests/knowledge/context/azure/test_postgresql_server.py
> +    @context(module_path="basic", test_options=TestOptions(run_drift_detection=False, run_cloudmapper=False))
remove the test options once you can

2021-12-22 14:21 UTC, Tomerva requested changes

2021-12-22 14:21 UTC, Tomerva commented on cloudrail/knowledge/context/azure/resources/databases/azure_postgresql_server_configuration.py
> +        self.with_aliases(f'{name}_{server_name}')
i dont think this is necessary as you dont use it, and (probably) your only usage for the collection of psql configs will be to assign them to the proper psql server, which doesnt require fast access to the configs (but does to the servers, which you already have)

2021-12-22 15:48 UTC, Imanuel-Mizrahi approved these changes

2021-12-22 15:48 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources/databases/azure_postgresql_server.py
> +    email_account_admins: Optional[bool]
please note all the optional fields, in most cases, bool is not an optional value.
In addition, I cannot see this class being used anywhere...
Perhaps we can remove it?

2021-12-27 09:59 UTC, Tomerva requested changes

2021-12-27 09:59 UTC, Tomerva commented on cloudrail/knowledge/context/azure/azure_relations_assigner.py
> +        postgresql_server.postgresql_configuration = ResourceInvalidator.get_by_logic(
is it possible that psql doesnt have config? if not, it should be invalidated

2021-12-27 09:59 UTC, Tomerva commented on cloudrail/knowledge/context/azure/resources/databases/azure_postgresql_server.py
> -        return {'tags': self.tags, 'server_name': self.server_name,
why removed tags?

2021-12-27 13:45 UTC, lirshindalman commented on cloudrail/knowledge/context/azure/azure_relations_assigner.py
> +        postgresql_server.postgresql_configuration = ResourceInvalidator.get_by_logic(
its possible that psql doesnt have config

2021-12-27 13:46 UTC, lirshindalman commented on cloudrail/knowledge/context/azure/resources/databases/azure_postgresql_server.py
> -        return {'tags': self.tags, 'server_name': self.server_name,
"tags" not needed in Azure resources, we collect it automatically in the builders.

2021-12-28 11:38 UTC, Tomerva approved these changes

2021-12-28 11:39 UTC, merged