CR-2158: [Not CAR] [AWS] Ensure ALB drops invalid HTTP headers
indeni/cloudrail-knowledge pull request #37
Opened 2021-05-24 12:35 UTC by Imanuel-Mizrahi

created new resource, added tests and rule

2021-05-24 15:44 UTC, yi2020 requested changes

2021-05-24 15:44 UTC, yi2020 commented on cloudrail/knowledge/context/aws/elb/load_balancer.py
> +        self.load_balancer_attributes: Optional[LoadBalancerAttributes] = None
Missing documentation

2021-05-24 15:44 UTC, yi2020 commented on cloudrail/knowledge/context/aws/elb/load_balancer_attributes.py
> +from typing import List
This file needs to be added to the elb readme in the docs

2021-05-24 15:44 UTC, yi2020 commented on cloudrail/knowledge/rules/aws/non_context_aware/protocol_enforcments/ensure_load_balancer_drops_invalid_http_headers_rule.py
> +            if lb.load_balancer_attributes and not lb.load_balancer_attributes.drop_invalid_header_fields:
Check if the lb is application-lb and not nlb.

2021-05-25 13:33 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/aws/non_context_aware/protocol_enforcments/ensure_load_balancer_drops_invalid_http_headers_rule.py
> +            if lb.load_balancer_attributes and not lb.load_balancer_attributes.drop_invalid_header_fields:
Code changed, @yi2020 , please review.
Thanks!

2021-05-25 13:37 UTC, yi2020 approved these changes

2021-05-27 05:51 UTC, merged