CR-3672: [Azure] [Context] Virtual Machine Scale Set Extension
indeni/cloudrail-knowledge pull request #370
Opened 2021-12-22 09:32 UTC by Imanuel-Mizrahi

added builders and test for the resource

2021-12-23 16:57 UTC, Imanuel-Mizrahi commented
While working on this PR, worked also on CR-3673, CR-3674, CR-3677

2021-12-26 08:51 UTC, Tomerva requested changes

2021-12-26 08:51 UTC, Tomerva commented on cloudrail/knowledge/context/azure/azure_relations_assigner.py
> +    def _assign_extension_to_vmss(vmss: AzureVirtualMachineScaleSet, vms_extentions: AliasesDict[AzureVirtualMachineExtension]):
you can improve this functions performance by running for each extension instead of for each vmss

then instead of using get_by_logic you can use get_by_id

2021-12-26 08:51 UTC, Tomerva commented on cloudrail/knowledge/context/azure/azure_relations_assigner.py
> +    def _assign_extension_to_vm(vm: AzureVirtualMachine, vms_extentions: AliasesDict[AzureVirtualMachineExtension]):
same as above

2021-12-26 08:51 UTC, Tomerva commented on tests/knowledge/rules/azure/context_aware/test_vmss_diagnostics_logs_enabled_rule.py
> +    def test_vmss_diagnostics_logs(self, unused_name: str, extnesion_configured: bool, should_alert: bool):
add tests for the different OS types, publishers, and extension types

2021-12-26 08:54 UTC, Imanuel-Mizrahi commented on tests/knowledge/rules/azure/context_aware/test_vmss_diagnostics_logs_enabled_rule.py
> +    def test_vmss_diagnostics_logs(self, unused_name: str, extnesion_configured: bool, should_alert: bool):
Basically, as far as I understand, we should more invest the effort on the TF tests using the main.tf files, and there we have enough scenarios.
If you think I should also make some scenarios here, will do.

2021-12-26 08:59 UTC, Tomerva commented on tests/knowledge/rules/azure/context_aware/test_vmss_diagnostics_logs_enabled_rule.py
> +    def test_vmss_diagnostics_logs(self, unused_name: str, extnesion_configured: bool, should_alert: bool):
its not alot of effort to add the test because it just means adding more parameters above and making it generic

2021-12-26 10:33 UTC, Tomerva approved these changes

2021-12-26 10:50 UTC, merged