Feature/cr 3684 event hub
indeni/cloudrail-knowledge pull request #371
Opened 2021-12-22 12:03 UTC by idan-aviv

2021-12-23 15:40 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/azure_relations_assigner.py
> +        event_hub.network_rule_set = network_rule_set
Should we put here some validation that we have "event_hub" before trying to access it?

2021-12-23 15:40 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources/event_hub/azure_event_hub_namespace.py
> +        self.with_aliases(self.namespace_id, self.name)
Are both the aliases (self.namespace_id, self.name) unique enough ?

2021-12-23 15:40 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources/event_hub/azure_event_hub_namespace.py
> +                 namespace_id: str,
why we had to use "namespace_id" and not the regular "_id" inherited from the AzureResource class?
In addition, if we add this attribute, we should add a doc_string to it.

2021-12-23 15:40 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources/event_hub/azure_event_hub_namespace.py
> +        return self.namespace_id
If at the end we won't use the "namespace_id" attributes, we should remove that

2021-12-23 15:40 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources/event_hub/event_hub_network_rule_set.py
> +            rule_set_id: network rule set id
Same query: why do we override here the "_id", using "rule_set_id"?

2021-12-23 15:40 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources/managed_identities/azure_user_assigned_identity.py
> +        return {}
If this resource is taggable, we should add the "self.tags" into the drift detection object

2021-12-23 15:40 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources_builders/scanner/event_hub/event_hub_namespace_builder.py
> +                                      namespace_id=attributes['id'],
I think there is no need to take the id, we are taking it by default for all Azure resources.

2021-12-23 15:40 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources_builders/terraform/assigned_user_identity_builder.py
> +        return AzureAssignedUserIdentity(identity_id=attributes['id'],
I do not think we need "attributes['id']" as I mentioned.

2021-12-26 08:16 UTC, idan-aviv commented on cloudrail/knowledge/context/azure/azure_relations_assigner.py
> +        event_hub.network_rule_set = network_rule_set
invalidator should throw exception if not found

2021-12-26 08:24 UTC, idan-aviv commented on cloudrail/knowledge/context/azure/resources/event_hub/azure_event_hub_namespace.py
> +        self.with_aliases(self.namespace_id, self.name)
@Imanuel-Mizrahi the id for sure....the name i believe unique for subscription as well...do you see any issue with that?

2021-12-26 08:30 UTC, Imanuel-Mizrahi approved these changes

2021-12-26 09:15 UTC, Tomerva requested changes

2021-12-26 09:15 UTC, Tomerva commented on cloudrail/knowledge/context/azure/resources/event_hub/azure_event_hub_namespace.py
> +        self.with_aliases(self.namespace_id, self.name)
usually we dont add the name as it is, as you said, unique only for a given subscription. if and when we add support for multi accounts, this will be problematic as it will require a really big change to support multi accounts

2021-12-26 09:15 UTC, Tomerva commented on cloudrail/knowledge/context/azure/resources/event_hub/azure_event_hub_namespace.py
> +        return self.namespace_id
i disagree, we should keep the id as it allows you to use AliasesDict, and when the id will be used, it will be a lot easier to integrate
also the id is something we use for numerous things in the framework, like showing the id of a resource in the evidence

2021-12-26 09:15 UTC, Tomerva commented on cloudrail/knowledge/context/azure/resources/webapp/azure_app_service.py
> +        self.managed_identities: List[AzureManagedIdentity] = []
add documentation

2021-12-26 09:15 UTC, Tomerva commented on cloudrail/knowledge/context/azure/resources/webapp/azure_function_app.py
> +        self.managed_identities: List[AzureManagedIdentity] = []
add documentation

2021-12-26 09:15 UTC, Tomerva commented on cloudrail/knowledge/context/azure/resources_builders/scanner/event_hub/event_hub_namespace_builder.py
> +                                      namespace_id=attributes['id'],
yeah, attribute['id'] is always mapped to object._id
and the implementation for get_id() is defaulted to `return self._id`

2021-12-26 09:15 UTC, Tomerva commented on cloudrail/knowledge/context/azure/resources_builders/scanner/event_hub/event_hub_network_rule_set_builder.py
> +                                    ],
fix indentation

2021-12-26 09:44 UTC, idan-aviv commented on cloudrail/knowledge/context/azure/resources/event_hub/event_hub_network_rule_set.py
> +            rule_set_id: network rule set id
@Imanuel-Mizrahi @Tomerva see EventHubNetworkRuleSetBuilder: 15 we need to parse the id and don't get from attributes['id'] so in this case i prefer to be more explicit but still if do you think it should be _id i'll change it NP

2021-12-26 10:02 UTC, Tomerva requested changes

2021-12-26 10:02 UTC, Tomerva commented on cloudrail/knowledge/context/azure/resources_builders/scanner/event_hub/event_hub_network_rule_set_builder.py
> +                                    ],
missed this

2021-12-26 10:02 UTC, Tomerva commented on cloudrail/knowledge/context/azure/resources_builders/terraform/assigned_user_identity_builder.py
> +        return AzureAssignedUserIdentity(identity_id=attributes['id'],
missed this

2021-12-26 10:11 UTC, idan-aviv commented on cloudrail/knowledge/context/azure/resources_builders/terraform/assigned_user_identity_builder.py
> +        return AzureAssignedUserIdentity(identity_id=attributes['id'],
@Tomerva see BaseAssignedUserIdentityBuilder: 17 we don't parse the id at the usual way

2021-12-26 10:12 UTC, idan-aviv commented on cloudrail/knowledge/context/azure/resources/webapp/azure_app_service.py
> +        self.managed_identities: List[AzureManagedIdentity] = []
@Tomerva but this property doesn't added by user (only by assigner)

2021-12-26 10:12 UTC, idan-aviv commented on cloudrail/knowledge/context/azure/resources/webapp/azure_function_app.py
> +        self.managed_identities: List[AzureManagedIdentity] = []
@Tomerva same as above

2021-12-26 12:41 UTC, Tomerva commented on cloudrail/knowledge/context/azure/resources/webapp/azure_app_service.py
> +        self.managed_identities: List[AzureManagedIdentity] = []
i think the point is to have doc for everything, as its main purpose is for building rules
dont see why the fact that its assigned by the assigner makes a difference

2021-12-27 07:52 UTC, Tomerva approved these changes

2021-12-27 07:52 UTC, Tomerva approved these changes

2021-12-27 08:09 UTC, merged