Cr 2468 not car azure ensure postgre sql servers have connection throttling enabled + CR-2469 Ensure PostgreSQL Servers have log checkpoints enabled
indeni/cloudrail-knowledge pull request #373
Opened 2021-12-26 12:32 UTC by lirshindalman

2021-12-27 07:09 UTC, Imanuel-Mizrahi requested changes

2021-12-27 07:09 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources/databases/azure_postgresql_server.py
> +        return {'name': self.name,
I think that the "name" should not be inside the drift detection object, as we cannot change it, without creating a new resource, and it's also being used in the "get_keys" (this is not your mistake, but I think we need to remove it now)
We need to add the "tags" again.
Probably now that we have many new fields, we should add it as well.

2021-12-27 07:09 UTC, Imanuel-Mizrahi approved these changes

2021-12-27 10:06 UTC, Tomerva requested changes

2021-12-27 10:06 UTC, Tomerva commented on cloudrail/knowledge/context/azure/azure_relations_assigner.py
> +        postgresql_server.postgresql_configuration = ResourceInvalidator.get_by_logic(
(last pr comment)
is it possible that psql doesnt have config? if not, it should be invalidated

2021-12-27 10:06 UTC, Tomerva commented on cloudrail/knowledge/context/azure/resources/databases/azure_postgresql_server.py
> +        return {'name': self.name,
1. add tags
2. get_keys should include subscription id

2021-12-27 10:06 UTC, Tomerva commented on cloudrail/knowledge/rules/azure/non_context_aware/abstract_postgresql_servers_have_configuration_value_enabled_rule.py
> +            if postgresql_servers.postgresql_configuration.name == self.get_configuration_type() and\
so i assume config is mandatory?..

2021-12-27 10:06 UTC, Tomerva commented on tests/knowledge/context/azure/test_postgresql_server.py
> +    @context(module_path="basic", test_options=TestOptions(run_drift_detection=False, run_cloudmapper=False))
remove test options?

2021-12-27 10:06 UTC, Tomerva commented on tests/knowledge/context/azure/test_postgresql_server_configuration.py
> +    @context(module_path="basic", test_options=TestOptions(run_drift_detection=False))
remove test options?

2021-12-29 09:48 UTC, Tomerva requested changes

2021-12-29 09:48 UTC, Tomerva commented on cloudrail/knowledge/rules/azure/non_context_aware/abstract_postgresql_servers_have_configuration_value_enabled_rule.py
> +                if postgresql_servers.postgresql_configuration.name == self.get_configuration_type() and\
im a little confused on why its called name but is checked against type

2021-12-29 09:55 UTC, Tomerva approved these changes

2021-12-29 10:19 UTC, merged