CR-2698: [AWS] [CFN] test_ec2
indeni/cloudrail-knowledge pull request #383
Opened 2021-12-30 17:12 UTC by Imanuel-Mizrahi

2022-01-02 07:23 UTC, idan-aviv commented on cloudrail/knowledge/context/aws/aws_relations_assigner.py
> +            if security_group.origin == EntityOrigin.CLOUDFORMATION and not security_group.outbound_permissions:
@Imanuel-Mizrahi how it is different from TF? it shouldn't be the same behavior?

2022-01-02 07:23 UTC, idan-aviv commented on cloudrail/knowledge/context/aws/aws_relations_assigner.py
> -            policy_arns = [pra.policy_arn for pra in policy_role_attachments if pra.role_name == role.role_name]
@Imanuel-Mizrahi why role name changed to aliases?

2022-01-02 07:23 UTC, idan-aviv commented on cloudrail/knowledge/context/aws/resources_builders/cloudformation/ec2/cloudformation_ec2_builder.py
> -        security_group_ids_from_enis = set(flat_list([ni['GroupSet'] for ni in network_interfaces if ni.get('GroupSet')]))
@Imanuel-Mizrahi please explain this change convert to: list->set->list

2022-01-02 07:23 UTC, idan-aviv commented on tests/knowledge/context/base_context_test.py
> -            self._run_drift_detection_for_cloudformation(module_path, test_options.cfn_template_params)
uncomment

2022-01-02 07:23 UTC, idan-aviv commented on cloudrail/knowledge/context/aws/cloudformation/aws_cloudformation_context_builder.py
>              s3_bucket_acls=CloudformationS3BucketAclBuilder(cfn_by_type_map).build(),
@Imanuel-Mizrahi shouldn't be new context test cases for those builders?

2022-01-02 07:38 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/aws_relations_assigner.py
> +            if security_group.origin == EntityOrigin.CLOUDFORMATION and not security_group.outbound_permissions:
I just tested it to make sure.
When you create a security group using TF, you can create it without ANY rules, and AWS will not fill it in for you.
But when you create one using CFN - AWS will automatically create this rule, as specified in the document I mentioned in the relations assigner, just before this function.
I actually found it while running CFN DD.

2022-01-02 07:39 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/aws_relations_assigner.py
> -            policy_arns = [pra.policy_arn for pra in policy_role_attachments if pra.role_name == role.role_name]
Because when running with CFN, the role name was not the actual role name, it was the resource CFN name (physical name?), I found that it was part of the aliases, so I used it, to cover all cases.

2022-01-02 07:40 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources_builders/cloudformation/ec2/cloudformation_ec2_builder.py
> -        security_group_ids_from_enis = set(flat_list([ni['GroupSet'] for ni in network_interfaces if ni.get('GroupSet')]))
using as a set - to remove duplicates.
Turning it back to a list - because otherwise there is a different type for this attribute - it failed the DD test for me.

2022-01-02 07:41 UTC, Imanuel-Mizrahi commented on tests/knowledge/context/base_context_test.py
> -            self._run_drift_detection_for_cloudformation(module_path, test_options.cfn_template_params)
Correct, my mistake, will change it ASAP.

2022-01-02 07:42 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/cloudformation/aws_cloudformation_context_builder.py
>              s3_bucket_acls=CloudformationS3BucketAclBuilder(cfn_by_type_map).build(),
Probably there should, but I just focused on EC2 tests, and I added the needed resources for my case.
There should be tickets for each one later.
Do you want me to take the other tickets, and work on it as part of this one?

2022-01-02 08:13 UTC, idan-aviv commented on cloudrail/knowledge/context/aws/aws_relations_assigner.py
> +            if security_group.origin == EntityOrigin.CLOUDFORMATION and not security_group.outbound_permissions:
@Imanuel-Mizrahi the real question is default security group do contains default outbound rule? in the actual environment? (no matter if AWS return it via API or not)

2022-01-02 08:16 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/aws_relations_assigner.py
> +            if security_group.origin == EntityOrigin.CLOUDFORMATION and not security_group.outbound_permissions:
yes, I saw it in the console while applying CFN.
Didn't see in the console, while applying with TF
In short: we have different behavior between CFN and TF

2022-01-02 08:29 UTC, idan-aviv commented on cloudrail/knowledge/context/aws/aws_relations_assigner.py
> -            policy_arns = [pra.policy_arn for pra in policy_role_attachments if pra.role_name == role.role_name]
in case of RoleName don't set explicitly the logical id will be the role name, so why "pra.role_name == role.role_name" don't find any matching?

2022-01-02 08:33 UTC, idan-aviv commented on cloudrail/knowledge/context/aws/cloudformation/aws_cloudformation_context_builder.py
>              s3_bucket_acls=CloudformationS3BucketAclBuilder(cfn_by_type_map).build(),
i think it is the correct way if we are adding new builders and want to be sure it's covered

2022-01-02 08:36 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/aws_relations_assigner.py
> -            policy_arns = [pra.policy_arn for pra in policy_role_attachments if pra.role_name == role.role_name]
@idan-aviv , cannot remember exactly, I know that is was not equal to the role_name, but only part of the aliases.
This is the CFN template:
```
  S3FullAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "s3-full-access-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: "*"
          Action:
          - sts:AssumeRole

  Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "allow_role_s3_operations"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:*"
            Resource: "*"
      Roles:
        - !Ref S3FullAccessRole
```
Inside the "policy" resource, you can see that the "Roles" is using Ref to the role resource.
What eventually I get into the role_name (inside the policy resource) is the value: "S3FullAccessRole", and not the role name ("s3-full-access-role").
I did find this value inside the aliases.
As the aliases, should be unique per resource, I didn't thought this should be an issue.

2022-01-02 08:36 UTC, idan-aviv commented on cloudrail/knowledge/context/aws/resources_builders/cloudformation/ec2/cloudformation_ec2_builder.py
> -        security_group_ids_from_enis = set(flat_list([ni['GroupSet'] for ni in network_interfaces if ni.get('GroupSet')]))
suggestion: you can add each sg id to set from the beginning and than convert it to list...your call

2022-01-02 08:36 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/cloudformation/aws_cloudformation_context_builder.py
>              s3_bucket_acls=CloudformationS3BucketAclBuilder(cfn_by_type_map).build(),
OK, will work on that, will let you know once ready

2022-01-02 08:41 UTC, Tomerva requested changes

2022-01-02 08:41 UTC, Tomerva commented on cloudrail/knowledge/context/aws/aws_relations_assigner.py
> +            if security_group.origin == EntityOrigin.CLOUDFORMATION and not security_group.outbound_permissions:
please add a comment explaining this

2022-01-02 08:41 UTC, Tomerva commented on cloudrail/knowledge/context/aws/aws_relations_assigner.py
> -            policy_arns = [pra.policy_arn for pra in policy_role_attachments if pra.role_name == role.role_name]
but is the role_name an alias? is it unique enough?

2022-01-02 08:41 UTC, Tomerva commented on cloudrail/knowledge/context/aws/cloudformation/aws_cloudformation_context_builder.py
>              s3_bucket_acls=CloudformationS3BucketAclBuilder(cfn_by_type_map).build(),
probably would be best, so if there are issues youll find them now

2022-01-02 08:47 UTC, idan-aviv commented on cloudrail/knowledge/context/aws/aws_relations_assigner.py
> -            policy_arns = [pra.policy_arn for pra in policy_role_attachments if pra.role_name == role.role_name]
ohhh o.k this test case ran without cfn-account-data so it is reasonable

2022-01-03 10:18 UTC, Tomerva requested changes

2022-01-03 10:18 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources/iam/iam_group.py
> +        return [self.account, self.name]
why did you need to change this? group_id is a perfectly good key

2022-01-03 10:18 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources/iam/iam_group.py
> +        return self.name
im not sure name is unique enough to be qualified as an id

2022-01-03 10:18 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources/iam/iam_user.py
> -        return [self.user_id]
why did you need to change this?

2022-01-03 10:18 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources/iam/iam_user.py
> +    def get_id(self) -> str:
im not sure name is unique enough to be qualified as an id

2022-01-03 10:18 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources/iam/policy_user_attachment.py
> +        return [self.policy_arn, self.user_name, self.account]
arn should be enough.. why change?

2022-01-03 11:55 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources/iam/iam_group.py
> +        return [self.account, self.name]
Answered internally, CFN does not provide us with the ID.

2022-01-03 11:56 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources/iam/iam_group.py
> +        return self.name
How much the value should be unique?
It's just that in CFN we need to return inside the "get_id" the value which CFN returns for the "Ref":
https://indeni.atlassian.net/wiki/spaces/RnD/pages/2330001409/Developing+new+CFN+builder+guide

2022-01-03 11:56 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources/iam/iam_user.py
> -        return [self.user_id]
Answered internally, CFN does not provide us with the ID.

2022-01-03 11:56 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources/iam/iam_user.py
> +    def get_id(self) -> str:
How much the value should be unique?
It's just that in CFN we need to return inside the "get_id" the value which CFN returns for the "Ref":
https://indeni.atlassian.net/wiki/spaces/RnD/pages/2330001409/Developing+new+CFN+builder+guide

2022-01-03 11:57 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources/iam/policy_user_attachment.py
> +        return [self.policy_arn, self.user_name, self.account]
Answered internally, CFN does not provide us with the ID.

2022-01-03 16:50 UTC, Tomerva approved these changes

2022-01-04 09:52 UTC, idan-aviv approved these changes

2022-01-04 09:53 UTC, merged