Feature/cr 3762 vnet
indeni/cloudrail-knowledge pull request #386
Opened 2022-01-02 12:08 UTC by idan-aviv

2022-01-03 07:30 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources/network/azure_virtual_network.py
> +        return {
Should we add 'tags' and 'cidr_addresses' to the drift object?

2022-01-03 07:30 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources_builders/scanner/subnet_builder.py
> +            if attributes['properties']['addressPrefix'] \
shouldn't we use "get"? or 'addressPrefix' will always be there but just empty?

2022-01-03 07:30 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources_builders/terraform/azure_terraform_builder.py
> -        resource.location = self._get_normalized_azure_location(attributes.get('location'))
Why did you removed the usage in "_get_normalized_azure_location" function?
It is needed in order to make sure that the location in TF and Live_env is the same syntax.

2022-01-03 07:30 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/terraform/azure_terraform_fields.yaml
> +      - location
I guess we can remove "location" it is a common field.

2022-01-03 10:04 UTC, Tomerva requested changes

2022-01-03 10:46 UTC, idan-aviv commented on cloudrail/knowledge/context/azure/resources_builders/terraform/azure_terraform_builder.py
> -        resource.location = self._get_normalized_azure_location(attributes.get('location'))
TF and Azure Rest API convert it to lower case with no white spaces...see in TestVirtualNetwork
@Imanuel-Mizrahi are you sure it is the case?

2022-01-03 10:49 UTC, idan-aviv commented on cloudrail/knowledge/context/azure/azure_relations_assigner.py
> +        vnet = ResourceInvalidator.get_by_id(virtual_networks, subnet.network_name, True, subnet)
see in AzureVirtualNetwork

2022-01-03 10:50 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources_builders/terraform/azure_terraform_builder.py
> -        resource.location = self._get_normalized_azure_location(attributes.get('location'))
@idan-aviv , this is why we created this function from the first place.
I noticed that while debugging, can you please run it in debug and see.
If you are correct - we can remove this function.
But this means there is a diff between Azure behavior now and the past...
Strange

2022-01-03 10:55 UTC, idan-aviv commented on cloudrail/knowledge/context/azure/azure_relations_assigner.py
> +        vnet = ResourceInvalidator.get_by_id(virtual_networks, subnet.network_name, True, subnet)
"subnet.network_name is globally unique name?"
it isn't but this is what TF using for assignment

```
resource "azurerm_subnet" "snet" {
  name                 = "${local.resource_prefix}-snet"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes     = ["10.5.25.0/24"]
}
```
@Tomerva any suggestions?

2022-01-04 08:37 UTC, Imanuel-Mizrahi approved these changes

2022-01-04 08:37 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/azure/resources_builders/common_resource_builder_functions.py
> +        return location_dict_map[location]
I think it would be best to implement as Tomer suggested:
return location_dict_map.get(location, location)

2022-01-04 08:57 UTC, Tomerva approved these changes

2022-01-04 11:39 UTC, merged