CR-3343: [AWS] [CFN] test_rds
indeni/cloudrail-knowledge pull request #390
Opened 2022-01-05 13:03 UTC by Imanuel-Mizrahi

2022-01-06 09:44 UTC, Tomerva requested changes

2022-01-06 09:44 UTC, Tomerva commented on cloudrail/knowledge/context/aws/scanner/aws_scanner_context_builder.py
> +                                   if any(igw.vpc_id == vpc.vpc_id for vpc in vpcs)])
why do you need this condition?

2022-01-06 09:46 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/scanner/aws_scanner_context_builder.py
> +                                   if any(igw.vpc_id == vpc.vpc_id for vpc in vpcs)])
I wanted to collect only the internet GW of the default VPC, not all IGW's.

2022-01-06 09:56 UTC, Imanuel-Mizrahi commented
Note about RDS instance engine_version value:
## Engine version is tricky, it depends on the engine_type, but for every type there is a different default version, and also depends on the region.
## There is an API call to get the default.
## Currently, I have removed "engine_version" from DD, we will fetch this data from the scanner context.
## Although "engine_version" attribute could be changed for RDS instance, but not from the RDS cluster.

2022-01-06 10:06 UTC, Tomerva commented on cloudrail/knowledge/context/aws/scanner/aws_scanner_context_builder.py
> +                                   if any(igw.vpc_id == vpc.vpc_id for vpc in vpcs)])
but we need igw for other vpc's....

2022-01-06 11:21 UTC, Tomerva approved these changes

2022-01-10 11:18 UTC, idan-aviv approved these changes

2022-01-10 11:41 UTC, merged