CR-3378: [AWS] [CFN] test_eks
indeni/cloudrail-knowledge pull request #392
Opened 2022-01-06 09:33 UTC by Imanuel-Mizrahi

modified cfn builders and test scenarios

2022-01-06 09:34 UTC, Imanuel-Mizrahi commented
I have removed a few fields from the dd object of EKS, since you can barely change any field after creation.

2022-01-06 11:13 UTC, Tomerva requested changes

2022-01-06 11:13 UTC, Tomerva commented on cloudrail/knowledge/context/aws/aws_relations_assigner.py
>              security_groups.update(security_group)
create_security_group already updates the context

2022-01-06 11:13 UTC, Tomerva commented on cloudrail/knowledge/context/aws/resources/eks/eks_cluster.py
> +        security_groups = self.security_group_ids
this initialization is redundant, please remove it
if the variable name was accurate it would be kinda fine, but the name is misleading, and creating an assignment for it doesnt really reduce amount of code

2022-01-06 11:52 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/resources/eks/eks_cluster.py
> +        security_groups = self.security_group_ids
Turns out that I need it, just because I added a logic in the relations assigner to check the value of this attribute.
Otherwise the code crashes...
Adding it back

2022-01-09 12:40 UTC, Tomerva requested changes

2022-01-09 12:40 UTC, Tomerva commented on cloudrail/knowledge/context/aws/aws_relations_assigner.py
> +        if eks_cluster.is_managed_by_iac and (eks_cluster.cluster_security_group_id is None or not eks_cluster.security_group_ids):
are you sure about this? this means that if he has a cluster SG but not "regular" SG's then it will create a pseudo one.. not sure this is what happens

2022-01-09 12:53 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/aws_relations_assigner.py
> +        if eks_cluster.is_managed_by_iac and (eks_cluster.cluster_security_group_id is None or not eks_cluster.security_group_ids):
I think you are right.
Based on this link:
https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html#:~:text=in%20their%20description.-,Note,-If%20you%20used
Sounds like it will take the default VPC SG.
Will try to change the logic accordingly once I can.

2022-01-09 16:40 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/aws_relations_assigner.py
> +        if eks_cluster.is_managed_by_iac and (eks_cluster.cluster_security_group_id is None or not eks_cluster.security_group_ids):
Done

2022-01-09 16:41 UTC, Tomerva approved these changes

2022-01-10 11:18 UTC, idan-aviv approved these changes

2022-01-10 12:12 UTC, merged