39 more doc updates
indeni/cloudrail-knowledge pull request #46
Opened 2021-05-26 05:21 UTC by yi2020

2021-05-26 05:53 UTC, alonashkenazi requested changes

2021-05-26 05:53 UTC, alonashkenazi commented on docs/context/aws/apigateway/README.md
> +## Sample rules
for all the samples, can you use snippet to include the code in the doc page so the reader will not need to redirect from this page?
https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippets

2021-05-26 19:42 UTC, yi2020 commented on docs/context/aws/apigateway/README.md
> +## Sample rules
Good idea, done:

<img width="723" alt="Screen Shot 2021-05-26 at 12 41 43 PM" src="https://user-images.githubusercontent.com/10076447/119721275-d31ba500-be1f-11eb-8118-96f37614f03b.png">
<img width="743" alt="Screen Shot 2021-05-26 at 12 41 36 PM" src="https://user-images.githubusercontent.com/10076447/119721279-d4e56880-be1f-11eb-8e35-6c730785f6fb.png">

2021-05-27 05:47 UTC, alonashkenazi approved these changes

2021-05-27 05:47 UTC, merged