Cr 2106 non car azure ensure no unused nsg exists
indeni/cloudrail-knowledge pull request #49
Opened 2021-05-26 11:33 UTC by olozz

2021-05-26 14:18 UTC, yi2020 commented
I recommend @Imanuel-Mizrahi reviews this too.

2021-05-26 14:26 UTC, yi2020 requested changes

2021-05-26 14:26 UTC, yi2020 commented on cloudrail/knowledge/context/azure/azure_resources/azure_resource.py
> -        self.azure_resource_type: str = azure_resource_type
Why was this removed?

2021-05-26 14:26 UTC, yi2020 commented on cloudrail/knowledge/context/azure/azure_resources/azure_resource_group.py
>      # todo - add CM/TF builders
All AzureResources need to have docstring documentation. Look at the resources in context/aws for examples. See how Attributes are documented there.

2021-05-26 14:26 UTC, yi2020 commented on cloudrail/knowledge/context/azure/azure_resources/nic/azure_nic.py
> +from typing import List, Optional
Regarding folder structure for AzureResources, in order to mirror the one for AWS:
* There is no need for `azure_resources` under `azure`.
* The names of the directories (like `nic` in this case) should mirror the names of the commands under Azure CLI. For example, `nic` is managed by `az network nic`, and so the directory structure should be `azure/network` (no need for a sub-directory `nic`). Similarly SQL servers would be under `azure/sql` because the command is `az sql`.

2021-05-26 14:26 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/unused_network_security_group_rule.py
> +            if not nsg.subnets and not nsg.network_interfaces:
If an NSG is used in a subnet, does that mean some resource is using it? Or it's just associated with a subnet?

2021-05-26 14:26 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/unused_network_security_group_rule.py
> +                        f'~{nsg.get_type()}~. '
When the evidence is a simple one line, like in this case, you can skip the line with ~ and just keep it to:
`f'{nsg.get_type()}  `{nsg.get_friendly_name()}` is unused`

2021-05-27 07:48 UTC, olozz commented on cloudrail/knowledge/context/azure/azure_resources/azure_resource.py
> -        self.azure_resource_type: str = azure_resource_type
no idea. It was Tomer who helped me to connect nsg-subnet.

2021-05-27 07:49 UTC, olozz commented on cloudrail/knowledge/context/azure/azure_resources/azure_resource_group.py
>      # todo - add CM/TF builders
added

2021-05-27 07:49 UTC, olozz commented on cloudrail/knowledge/context/azure/azure_resources/nic/azure_nic.py
> +from typing import List, Optional
the structure was done before. adjusted as required.

2021-05-27 07:50 UTC, olozz commented on cloudrail/knowledge/rules/azure/non_context_aware/unused_network_security_group_rule.py
> +            if not nsg.subnets and not nsg.network_interfaces:
it means that all resources connected to the subnet will use it.

2021-05-27 07:50 UTC, olozz commented on cloudrail/knowledge/rules/azure/non_context_aware/unused_network_security_group_rule.py
> +                        f'~{nsg.get_type()}~. '
adjusted

2021-05-27 12:38 UTC, Tomerva commented on cloudrail/knowledge/context/azure/azure_resources/azure_resource.py
> -        self.azure_resource_type: str = azure_resource_type
We dont use it, and its not clear what should be filled here

2021-05-27 14:50 UTC, olozz commented on tests/knowledge/rules/azure/non_context_aware/test_ensure_no_unused_nsg.py
> +        #context = AzureEnvironmentContext(net_security_groups=[nsg])
removed

2021-05-30 09:25 UTC, Imanuel-Mizrahi approved these changes

2021-05-30 13:59 UTC, alonashkenazi submitted a review, later dismissed

2021-06-01 06:36 UTC, olozz commented on cloudrail/knowledge/context/azure/network/azure_nic.py
> +    def get_cloud_resource_url(self) -> Optional[str]:
to construct uri we need to use  tenant id which I dont know where to get from

2021-06-01 06:36 UTC, olozz commented on cloudrail/knowledge/context/azure/network/azure_nsg.py
> +                network_interfaces=None,
adjusted

2021-06-01 06:37 UTC, olozz commented on cloudrail/knowledge/context/azure/network/azure_nsg.py
> +                subnets=None) -> None:
adjusted

2021-06-01 06:37 UTC, olozz commented on tests/knowledge/rules/azure/non_context_aware/test_ensure_no_unused_nsg.py
> +        nsg.network_interfaces=["mynic"]
adjusted

2021-06-01 20:42 UTC, yi2020 requested changes

2021-06-01 20:42 UTC, yi2020 commented on cloudrail/knowledge/context/azure/azure_resources/databases/azure_sql_server.py
>  class AzureSqlServer(AzureResource):
Missing documentation

2021-06-01 20:42 UTC, yi2020 commented on cloudrail/knowledge/context/azure/azure_resources/web_app/azure_app_service.py
>  class AzureAppService(AzureResource):
Missing documentation

2021-06-01 20:42 UTC, yi2020 commented on cloudrail/version.py
> +__version__ = 'v0.0.27-beta.2'
I don't think this change was supposed to be here @alonashkenazi ?

2021-06-02 12:29 UTC, Tomerva commented on cloudrail/knowledge/context/azure/azure_resources/databases/azure_sql_server.py
>  class AzureSqlServer(AzureResource):
Added

2021-06-02 12:29 UTC, Tomerva commented on cloudrail/knowledge/context/azure/azure_resources/web_app/azure_app_service.py
>  class AzureAppService(AzureResource):
Please ignore this for this PR. There was some confusion with this resource. My next task is on AppService and i will add the docs there.

2021-06-02 18:57 UTC, yi2020 commented on cloudrail/knowledge/context/azure/azure_resources/databases/azure_sql_server.py
>  class AzureSqlServer(AzureResource):
Where?

2021-06-03 06:37 UTC, Tomerva commented on cloudrail/version.py
> +__version__ = 'v0.0.27-beta.2'
this is how we update the version file
when doing release, we push version.py with the new version

2021-06-03 07:05 UTC, Tomerva commented on cloudrail/knowledge/context/azure/azure_resources/databases/azure_sql_server.py
>  class AzureSqlServer(AzureResource):
it was showing old revision for some reason.. now you can see the latest changes

2021-06-03 17:58 UTC, yi2020 commented
@olozz @Tomerva please fix the directory structure. I also posted this as a comment on Slack for you both now. I've put this twice as comments on PRs here but it doesn't look like this was resolved.

2021-06-06 08:26 UTC, merged