CR-2098-fix_should_run_rule_to_remove_account
indeni/cloudrail-knowledge pull request #51
Opened 2021-05-30 06:45 UTC by Imanuel-Mizrahi

modified needed rules, to not use account as mandate

2021-05-30 07:30 UTC, Imanuel-Mizrahi commented
Following this code change, all unit-tests passed with ratio = 0:https://jenkins.aws.indeni-ops.com/job/Cloudrail-unit-tests/506/

2021-05-30 07:34 UTC, alonashkenazi requested changes

2021-05-30 07:34 UTC, alonashkenazi commented on cloudrail/version.py
> +__version__ = 'v0.0.25-beta.1'
you shouldn't commit beta

2021-05-30 07:35 UTC, Imanuel-Mizrahi commented on cloudrail/version.py
> +__version__ = 'v0.0.25-beta.1'
@alonashkenazi , this was done automatically.
How can I avoid that?

2021-05-30 07:40 UTC, alonashkenazi commented on cloudrail/version.py
> +__version__ = 'v0.0.25-beta.1'
commit __version__ = 'v0.0.24' back

2021-05-30 08:02 UTC, alonashkenazi approved these changes

2021-05-30 16:05 UTC, Imanuel-Mizrahi commented
Tested this changes using cloudrail CLI, all affected rules listed in the ticket - passed.

2021-05-30 19:38 UTC, Tomerva approved these changes

2021-05-31 13:58 UTC, yi2020 requested changes

2021-05-31 13:58 UTC, yi2020 commented on cloudrail/knowledge/context/aws/iam/iam_password_policy.py
> +            return 'The account'
Should this be "the account's policy"?

2021-05-31 14:03 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/iam/iam_password_policy.py
> +            return 'The account'
Worth thinking of it. we are dealing with the IAM account pass policy.
Perhaps we should change it to:
if self.account:
  return f'IAM account password policy for account {self.account}'
else:
  return 'IAM account password policy'
?

2021-06-01 04:48 UTC, yi2020 commented on cloudrail/knowledge/context/aws/iam/iam_password_policy.py
> +            return 'The account'
That works

2021-06-01 05:40 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/iam/iam_password_policy.py
> +            return 'The account'
OK @yi2020 , change made

2021-06-02 20:20 UTC, yi2020 approved these changes

2021-06-03 05:54 UTC, merged