Cr 2256
indeni/cloudrail-knowledge pull request #52
Opened 2021-05-31 13:13 UTC by Tomerva

2021-06-01 06:34 UTC, alonashkenazi approved these changes

2021-06-01 06:34 UTC, alonashkenazi commented on tests/knowledge/rules/azure/non_context_aware/test_app_service_ftps_required.py
> +    def test_all_allowed_state(self):
maybe you can use @pytest.mark.parametrize and have only 1 test method
https://docs.pytest.org/en/6.2.x/parametrize.html

2021-06-01 06:34 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/azure_resources/app_service/azure_app_service_config.py
> +                         'App Service Config', AzureResourceType.NONE)
Shouldn't we add AzureResourceType.APP_CONFIG?

2021-06-01 06:34 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/azure_resources/app_service/azure_app_service.py
>  class AzureAppService(AzureResource):
Documentation

2021-06-01 06:34 UTC, alonashkenazi commented on cloudrail/knowledge/context/azure/azure_resources/app_service/azure_app_service_config.py
> +class AzureAppServiceConfig(AzureResource):
Documentation

2021-06-01 06:46 UTC, Tomerva commented on cloudrail/knowledge/context/azure/azure_resources/app_service/azure_app_service_config.py
> +                         'App Service Config', AzureResourceType.NONE)
Its because it doesnt exist in terraform
this is just an enum to declare what type of terraform-object it is (like aws_vpc)

2021-06-01 20:40 UTC, yi2020 approved these changes
Other than documentation, LGTM

2021-06-06 11:46 UTC, Tomerva commented on tests/knowledge/rules/azure/non_context_aware/test_function_app_enforces_ftps.py
> +# from unittest import TestCase
temporarily commented out since there was a confusion with the objects. will be fixed by Idan

2021-06-06 11:46 UTC, Tomerva commented on cloudrail/knowledge/rules/azure/non_context_aware/function_app_enforces_ftps_only_rule.py
> +# from typing import Dict, List
temporarily commented out since there was a confusion with the objects. will be fixed by Idan

2021-06-06 13:44 UTC, alonashkenazi requested changes

2021-06-06 13:44 UTC, alonashkenazi commented on cloudrail/knowledge/context/mergeable.py
> +    def is_managed_by_terraform(self) -> bool:
Where are you using it? and why not using `is_managed_by_iac`?

2021-06-06 13:44 UTC, alonashkenazi commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_ftps_required.py
> +class AppServiceFtpsRequired(AzureBaseRule):
Should the rule class name end with Rule? Should the file name end with _rule? what is our standard?

2021-06-06 14:01 UTC, alonashkenazi requested changes

2021-06-06 14:01 UTC, alonashkenazi commented on d.py
> +import os
what is this file?

2021-06-06 16:28 UTC, Tomerva commented on cloudrail/knowledge/context/mergeable.py
> +    def is_managed_by_terraform(self) -> bool:
it was used in relation assigner, but now looking at it again its enough to know its managed by iac

2021-06-06 16:35 UTC, Tomerva commented on cloudrail/knowledge/rules/azure/non_context_aware/app_service_ftps_required.py
> +class AppServiceFtpsRequired(AzureBaseRule):
fixed

2021-06-07 06:41 UTC, Tomerva commented on d.py
> +import os
didnt mean to commit that.. removed

2021-06-07 08:24 UTC, alonashkenazi approved these changes

2021-06-07 08:25 UTC, merged