FunctionAppAuthenticationEnableRule: new azure rule
indeni/cloudrail-knowledge pull request #55
Opened 2021-06-02 11:11 UTC by idan-aviv

2021-06-02 11:17 UTC, Imanuel-Mizrahi commented on cloudrail/version.py
> +__version__ = 'v0.0.27-beta.4'
as far as I know, we do not push beta, so that should be changed

2021-06-02 11:17 UTC, Imanuel-Mizrahi approved these changes

2021-06-02 11:28 UTC, idan-aviv commented on cloudrail/version.py
> +__version__ = 'v0.0.27-beta.4'
@Imanuel-Mizrahi i didn't change it, its automatically added by github flow when you deploy to pipy

2021-06-02 18:19 UTC, yi2020 requested changes

2021-06-02 18:19 UTC, yi2020 commented on cloudrail/knowledge/context/azure/azure_resources/web_app/azure_function_app.py
> +class AzureFunctionApp(AzureResource):
Missing docs

2021-06-02 18:19 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/function_app_authentication_enable_rule.py
> +        for func_app in env_context.function_apps.values():
Why do you need .values() ? When using the context in AWS, we don't need .values()

2021-06-02 18:19 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/function_app_authentication_enable_rule.py
> +        for func_app in env_context.function_apps.values():
(or in other words, why use AliasesDict)

2021-06-02 18:19 UTC, yi2020 commented on cloudrail/knowledge/context/azure/azure_resources/web_app/azure_function_app.py
> +from typing import Optional, List
Can you `git mv` everything under azure_resources to simply azure, so it matches the directory structure we have for `/context/aws`? I know it's not part of this rule, but I've already asked for this in another PR and it wasn't done.

2021-06-03 06:48 UTC, Tomerva commented on cloudrail/knowledge/rules/azure/non_context_aware/function_app_authentication_enable_rule.py
> +        for func_app in env_context.function_apps.values():
keep using AliasesDict, theres just no need to do .values() when iterating

2021-06-03 06:50 UTC, Tomerva commented on cloudrail/version.py
> +__version__ = 'v0.0.27-beta.4'
when you do release, it automatically modifies version.py to include the new version

2021-06-07 03:28 UTC, yi2020 approved these changes

2021-06-07 06:33 UTC, merged