Cr 2219
indeni/cloudrail-knowledge pull request #56
Opened 2021-06-02 16:01 UTC by Tomerva

2021-06-02 18:59 UTC, yi2020 requested changes

2021-06-02 18:59 UTC, yi2020 commented on cloudrail/knowledge/context/aws/ec2/security_group.py
> +        return any(resource for resource in self._used_by if not isinstance(resource, NetworkInterface) or resource.owner)
I thought we discussed using a flag, so that if invalidation removes the interfaces from this resource is_used will still be True?

2021-06-03 06:34 UTC, Tomerva commented on cloudrail/knowledge/context/aws/ec2/security_group.py
> +        return any(resource for resource in self._used_by if not isinstance(resource, NetworkInterface) or resource.owner)
yeah, if the attached ENI or its owner are invalid the result will still be True

2021-06-03 09:22 UTC, Tomerva commented on cloudrail/knowledge/context/aws/ec2/security_group.py
> +        return any(resource for resource in self._used_by if not isinstance(resource, NetworkInterface) or resource.owner)
just to be clear, invalidation process doesnt remove the link between resources, it removes the invalidated resource from the context object

so for example if you have a Subnet and it has a link to a Vpc thats invalidated, subnet will be removed from environment_context.subnets, vpc will be removed from environment_context.vpcs, but subnet.vpc will remain

2021-06-03 18:01 UTC, yi2020 commented
Oh I didn't realize that. It wasn't a problem because both vpc and subnet
are removed, so it's not possible to get from the vpc to the subnet or vice
versa. Understood.

On Thu, Jun 3, 2021 at 2:22 AM Tomerva ***@***.***> wrote:

> *@Tomerva* commented on this pull request.
> ------------------------------
>
> In cloudrail/knowledge/context/aws/ec2/security_group.py
> <https://github.com/indeni/cloudrail-knowledge/pull/56#discussion_r644633541>
> :
>
> > @@ -37,9 +37,13 @@ def __init__(self, security_group_id: str, region: str, account: str,
>          self._used_by: Set[AwsResource] = set()
>
>      @property
> -    def used_by(self) -> Set[AwsResource]:
> -        return {resource for resource in self._used_by if not resource.is_invalidated and
> -                (not isinstance(resource, NetworkInterface) or (resource.owner and not resource.owner.is_invalidated))}
> +    def is_used(self) -> bool:
> +        """
> +        This property returns true if any resource is using this security group, including invalidated resources.
> +
> +        Note: Network interfaces that use this security group, but are not attached to a resource, will not count.
> +        """
> +        return any(resource for resource in self._used_by if not isinstance(resource, NetworkInterface) or resource.owner)
>
> just to be clear, invalidation process doesnt remove the link between
> resources, it removes the invalidated resource from the context object
>
> so for example if you have a Subnet and it has a link to a Vpc thats
> invalidated, subnet will be removed from environment_context.subnets, vpc
> will be removed from environment_context.vpcs, but subnet.vpc will remain
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/indeni/cloudrail-knowledge/pull/56#discussion_r644633541>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACM4CH5YVXRKI5QOXXVTFQ3TQ5CWNANCNFSM457BGKIQ>
> .
>

2021-06-03 18:02 UTC, yi2020 approved these changes

2021-06-06 13:48 UTC, alonashkenazi approved these changes

2021-06-06 16:37 UTC, merged