Cr 2142 vpn rule
indeni/cloudrail-knowledge pull request #68
Opened 2021-06-08 06:31 UTC by Tomerva

2021-06-08 16:27 UTC, yi2020 requested changes

2021-06-08 16:27 UTC, yi2020 commented on cloudrail/knowledge/context/azure/network/azure_vnet_gateway.py
> +from enum import Enum
Please add this file to the Azure context documentation, per message in Slack on #cloudrail-knowledge-developers

2021-06-13 08:01 UTC, Tomerva commented on cloudrail/knowledge/context/azure/network/azure_vnet_gateway.py
> +from enum import Enum
Fixed, please re-review

2021-06-13 09:33 UTC, Viperain approved these changes

2021-06-16 09:18 UTC, merged