Added AutoProvisioningLogAnalyticsAgentDisabledRule
indeni/cloudrail-knowledge pull request #75
Opened 2021-06-08 15:18 UTC by Tomerva

2021-06-08 16:57 UTC, yi2020 requested changes

2021-06-08 16:57 UTC, yi2020 commented on cloudrail/knowledge/context/azure/security/azure_security_center_auto_provisioning.py
> +from typing import List, Optional
Please add to the documentation (per Slack message again)

2021-06-09 08:47 UTC, Tomerva commented on cloudrail/knowledge/context/azure/security/azure_security_center_auto_provisioning.py
> +from typing import List, Optional
added

2021-06-15 14:23 UTC, yi2020 approved these changes

2021-06-17 08:49 UTC, Imanuel-Mizrahi approved these changes

2021-06-17 11:41 UTC, merged