CR-1264: [Non-CAR][AWS] Lambda function can be invoked by anonymous or all AWS authenticated users
indeni/cloudrail-knowledge pull request #76
Opened 2021-06-09 16:10 UTC by Imanuel-Mizrahi

rule ready

2021-06-09 21:04 UTC, yi2020 requested changes

2021-06-10 06:35 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/aws/non_context_aware/ensure_lambda_function_cannot_be_invoked_public_rule.py
> +                   and any(action in ('*', 'lambda:InvokeFunction', 'lambda:*') for action in statement.actions)
@yi2020 , I have changed it, to use get_intersected_actions() function, please review.
Thanks!

2021-06-10 16:06 UTC, yi2020 approved these changes

2021-06-16 14:18 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/lambda_/lambda_policy_statements.py
> +
@idan-aviv , please take a look at the changes I have made here.
and also in the relations assigner here:
https://bitbucket.org/indeni/cloud-rail/pull-requests/1415#chg-src/core/aws/aws_relations_assigner.py
Thanks!

2021-07-14 10:12 UTC, Tomerva commented on cloudrail/knowledge/utils/arn_utils.py
> +def are_arns_intersected_for_tf(resource_arn: str, target_arn: str):
this code is duplicated
remove are_arns_intersected, and rename this function to are_arns_intersected

then all thats left is:
resource_arn_parsed = arnparse(resource_arn) if is_valid_arn(resource_arn) else DummyArnObject(resource_arn)
and same for target_arn_parsed

2021-07-14 10:22 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/utils/arn_utils.py
> +def are_arns_intersected_for_tf(resource_arn: str, target_arn: str):
Actually, it's almost true.
They are not 100% identical, there is also another line which I do not run for TF:
        elif not (is_valid_arn(resource_arn) and is_valid_arn(target_arn)):
            return False
I was thinking about adding a flag to the function, that will run this if condition only if it's TF.
What do you think @Tomerva ?

2021-07-14 10:47 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/utils/arn_utils.py
> +def are_arns_intersected_for_tf(resource_arn: str, target_arn: str):
@Tomerva , looking at the usage of "are_arns_intersected" in a few places inside the project, it might be better to add the resource object itself, in order to check if it's TF or not, and then decide.
Might need to zoom on that and decide...

2021-07-21 09:15 UTC, Tomerva commented on cloudrail/knowledge/context/aws/lambda_/lambda_function.py
> +    def is_arn_match_for_lambda(self, arn: str):
there is no need to create a new function called is_arn_match_for_lambda
instead, keep it is_arn_match. then when you have a resource and you want to do resource.is_arn_match, you wont have to 'know' if resource is of type lambda

LMK if you need explanation on how this works

2021-07-21 09:17 UTC, Tomerva commented on cloudrail/knowledge/rules/aws/non_context_aware/ensure_lambda_function_cannot_be_invoked_public_rule.py
> +            return issues
indentation is not good

2021-07-21 09:46 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/lambda_/lambda_function.py
> +    def is_arn_match_for_lambda(self, arn: str):
Won't it be an issue, if the resource is defined as "AwsResource", and then it will take the "is_arn_match" function for "AwsResource" class, instead of Lambda_function class?

2021-07-21 09:46 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/context/aws/lambda_/lambda_function.py
> +    def is_arn_match_for_lambda(self, arn: str):
@Tomerva , please see my query here. Thanks!

2021-07-21 13:23 UTC, Tomerva approved these changes

2021-07-22 07:09 UTC, idan-aviv approved these changes

2021-07-22 07:34 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/aws/non_context_aware/ensure_lambda_function_cannot_be_invoked_public_rule.py
> +                   and get_intersected_actions(statement.actions, 'lambda:InvokeFunction')
@idan-aviv , please check the ticket https://indeni.atlassian.net/browse/CR-1264, the conditions were set according to the logic inside the ticket.
This is not only "publicly" invoked, we also would like to avoid all AWS authenticated users and services, the name of this function may be misleading, as well as the name of the rule...
For the moment, I will not change it, as the conditions are fixed per the logic in the ticket, and should be used specifically here, so I will not move it as a property inside the lambda_function object.

2021-07-22 07:34 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/aws/non_context_aware/ensure_lambda_function_cannot_be_invoked_public_rule.py
> +    @staticmethod
replied inside the next comment

2021-07-22 16:10 UTC, merged