CR-2271: [Not CAR] [Azure] Ensure Function App is using the latest TLS version
indeni/cloudrail-knowledge pull request #91
Opened 2021-06-15 11:22 UTC by Imanuel-Mizrahi

Added attributes, rules and tests

2021-06-15 12:25 UTC, yi2020 approved these changes

2021-06-15 12:26 UTC, yi2020 requested changes

2021-06-15 12:26 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/azure_rules_metadata.yaml
> +      Follow the guide at <https://azure.microsoft.com/en-us/blog/announcing-http-2-support-in-azure-app-service/>
Remediation steps are wrong

2021-06-15 12:27 UTC, yi2020 requested changes

2021-06-15 12:27 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/function_app_use_latest_tls_version_rule.py
> +                        f'The {func_app.get_type()} `{func_app.get_friendly_name()}` does not use the latest TLS version.',
Let's do:
```
                        f'The {func_app.get_type()} `{func_app.get_friendly_name()}` uses `{func_app.minimum_tls_version }` instead of 1.2.',
```

2021-06-15 12:28 UTC, Tomerva approved these changes

2021-06-16 06:02 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/azure/azure_rules_metadata.yaml
> +      Follow the guide at <https://azure.microsoft.com/en-us/blog/announcing-http-2-support-in-azure-app-service/>
fixed

2021-06-16 06:04 UTC, Imanuel-Mizrahi commented on cloudrail/knowledge/rules/azure/non_context_aware/function_app_use_latest_tls_version_rule.py
> +                        f'The {func_app.get_type()} `{func_app.get_friendly_name()}` does not use the latest TLS version.',
Fixed it, but perhaps it should be detailed?:
f'The {func_app.get_type()} `{func_app.get_friendly_name()}` uses `{func_app.minimum_tls_version }` for the minimum TLS version, instead of 1.2.',
?

2021-06-16 18:20 UTC, yi2020 commented on cloudrail/knowledge/rules/azure/non_context_aware/function_app_use_latest_tls_version_rule.py
> +                        f'The {func_app.get_type()} `{func_app.get_friendly_name()}` does not use the latest TLS version.',
Even better

2021-06-17 15:28 UTC, yi2020 approved these changes

2021-06-17 16:11 UTC, merged